// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/oss/v1/oss.proto

package oss_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBiz int32

const (
	UploadBiz_UPLOAD_BIZ_UNSPECIFIED             UploadBiz = 0
	UploadBiz_UPLOAD_BIZ_USER_AVATAR             UploadBiz = 1
	UploadBiz_UPLOAD_BIZ_INTERVIEW_QUESTION_BANK UploadBiz = 2
)

// Enum value maps for UploadBiz.
var (
	UploadBiz_name = map[int32]string{
		0: "UPLOAD_BIZ_UNSPECIFIED",
		1: "UPLOAD_BIZ_USER_AVATAR",
		2: "UPLOAD_BIZ_INTERVIEW_QUESTION_BANK",
	}
	UploadBiz_value = map[string]int32{
		"UPLOAD_BIZ_UNSPECIFIED":             0,
		"UPLOAD_BIZ_USER_AVATAR":             1,
		"UPLOAD_BIZ_INTERVIEW_QUESTION_BANK": 2,
	}
)

func (x UploadBiz) Enum() *UploadBiz {
	p := new(UploadBiz)
	*p = x
	return p
}

func (x UploadBiz) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadBiz) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_oss_v1_oss_proto_enumTypes[0].Descriptor()
}

func (UploadBiz) Type() protoreflect.EnumType {
	return &file_api_proto_oss_v1_oss_proto_enumTypes[0]
}

func (x UploadBiz) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadBiz.Descriptor instead.
func (UploadBiz) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{0}
}

type SignUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           UploadBiz              `protobuf:"varint,1,opt,name=Biz,proto3,enum=oss.v1.UploadBiz" json:"Biz,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUploadRequest) Reset() {
	*x = SignUploadRequest{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUploadRequest) ProtoMessage() {}

func (x *SignUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUploadRequest.ProtoReflect.Descriptor instead.
func (*SignUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{0}
}

func (x *SignUploadRequest) GetBiz() UploadBiz {
	if x != nil {
		return x.Biz
	}
	return UploadBiz_UPLOAD_BIZ_UNSPECIFIED
}

func (x *SignUploadRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SignUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type SignUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=Dir,proto3" json:"Dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUploadResponse) Reset() {
	*x = SignUploadResponse{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUploadResponse) ProtoMessage() {}

func (x *SignUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUploadResponse.ProtoReflect.Descriptor instead.
func (*SignUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{1}
}

func (x *SignUploadResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *SignUploadResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type UploadCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCallbackRequest) Reset() {
	*x = UploadCallbackRequest{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCallbackRequest) ProtoMessage() {}

func (x *UploadCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCallbackRequest.ProtoReflect.Descriptor instead.
func (*UploadCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{2}
}

func (x *UploadCallbackRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadCallbackRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *UploadCallbackRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type UploadCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           UploadBiz              `protobuf:"varint,1,opt,name=Biz,proto3,enum=oss.v1.UploadBiz" json:"Biz,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ObjectName    string                 `protobuf:"bytes,3,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	SourceFile    string                 `protobuf:"bytes,4,opt,name=SourceFile,proto3" json:"SourceFile,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCallbackResponse) Reset() {
	*x = UploadCallbackResponse{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCallbackResponse) ProtoMessage() {}

func (x *UploadCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCallbackResponse.ProtoReflect.Descriptor instead.
func (*UploadCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{3}
}

func (x *UploadCallbackResponse) GetBiz() UploadBiz {
	if x != nil {
		return x.Biz
	}
	return UploadBiz_UPLOAD_BIZ_UNSPECIFIED
}

func (x *UploadCallbackResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UploadCallbackResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *UploadCallbackResponse) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *UploadCallbackResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type GetObjectURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectURLRequest) Reset() {
	*x = GetObjectURLRequest{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectURLRequest) ProtoMessage() {}

func (x *GetObjectURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectURLRequest.ProtoReflect.Descriptor instead.
func (*GetObjectURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectURLRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type GetObjectURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectURLResponse) Reset() {
	*x = GetObjectURLResponse{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectURLResponse) ProtoMessage() {}

func (x *GetObjectURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectURLResponse.ProtoReflect.Descriptor instead.
func (*GetObjectURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectURLResponse) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_oss_v1_oss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_oss_v1_oss_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_oss_v1_oss_proto protoreflect.FileDescriptor

const file_api_proto_oss_v1_oss_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/oss/v1/oss.proto\x12\x06oss.v1\"l\n" +
	"\x11SignUploadRequest\x12#\n" +
	"\x03Biz\x18\x01 \x01(\x0e2\x11.oss.v1.UploadBizR\x03Biz\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x1a\n" +
	"\bFileName\x18\x03 \x01(\tR\bFileName\"B\n" +
	"\x12SignUploadResponse\x12\x1a\n" +
	"\bResponse\x18\x01 \x01(\tR\bResponse\x12\x10\n" +
	"\x03Dir\x18\x02 \x01(\tR\x03Dir\"c\n" +
	"\x15UploadCallbackRequest\x12\x16\n" +
	"\x06Bucket\x18\x01 \x01(\tR\x06Bucket\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x02 \x01(\tR\n" +
	"ObjectName\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\tR\x04Size\"\xa9\x01\n" +
	"\x16UploadCallbackResponse\x12#\n" +
	"\x03Biz\x18\x01 \x01(\x0e2\x11.oss.v1.UploadBizR\x03Biz\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x03 \x01(\tR\n" +
	"ObjectName\x12\x1e\n" +
	"\n" +
	"SourceFile\x18\x04 \x01(\tR\n" +
	"SourceFile\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\tR\x04Size\"5\n" +
	"\x13GetObjectURLRequest\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x01 \x01(\tR\n" +
	"ObjectName\"(\n" +
	"\x14GetObjectURLResponse\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse*k\n" +
	"\tUploadBiz\x12\x1a\n" +
	"\x16UPLOAD_BIZ_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16UPLOAD_BIZ_USER_AVATAR\x10\x01\x12&\n" +
	"\"UPLOAD_BIZ_INTERVIEW_QUESTION_BANK\x10\x022\xb5\x02\n" +
	"\n" +
	"OSSService\x12C\n" +
	"\n" +
	"SignUpload\x12\x19.oss.v1.SignUploadRequest\x1a\x1a.oss.v1.SignUploadResponse\x12O\n" +
	"\x0eUploadCallback\x12\x1d.oss.v1.UploadCallbackRequest\x1a\x1e.oss.v1.UploadCallbackResponse\x12I\n" +
	"\fGetObjectURL\x12\x1b.oss.v1.GetObjectURLRequest\x1a\x1c.oss.v1.GetObjectURLResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.oss.v1.HealthCheckRequest\x1a\x1b.oss.v1.HealthCheckResponseB:Z8github.com/yzletter/go-postery/api/proto/oss/v1;oss_grpcb\x06proto3"

var (
	file_api_proto_oss_v1_oss_proto_rawDescOnce sync.Once
	file_api_proto_oss_v1_oss_proto_rawDescData []byte
)

func file_api_proto_oss_v1_oss_proto_rawDescGZIP() []byte {
	file_api_proto_oss_v1_oss_proto_rawDescOnce.Do(func() {
		file_api_proto_oss_v1_oss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_oss_v1_oss_proto_rawDesc), len(file_api_proto_oss_v1_oss_proto_rawDesc)))
	})
	return file_api_proto_oss_v1_oss_proto_rawDescData
}

var file_api_proto_oss_v1_oss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_oss_v1_oss_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_oss_v1_oss_proto_goTypes = []any{
	(UploadBiz)(0),                 // 0: oss.v1.UploadBiz
	(*SignUploadRequest)(nil),      // 1: oss.v1.SignUploadRequest
	(*SignUploadResponse)(nil),     // 2: oss.v1.SignUploadResponse
	(*UploadCallbackRequest)(nil),  // 3: oss.v1.UploadCallbackRequest
	(*UploadCallbackResponse)(nil), // 4: oss.v1.UploadCallbackResponse
	(*GetObjectURLRequest)(nil),    // 5: oss.v1.GetObjectURLRequest
	(*GetObjectURLResponse)(nil),   // 6: oss.v1.GetObjectURLResponse
	(*HealthCheckRequest)(nil),     // 7: oss.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 8: oss.v1.HealthCheckResponse
}
var file_api_proto_oss_v1_oss_proto_depIdxs = []int32{
	0, // 0: oss.v1.SignUploadRequest.Biz:type_name -> oss.v1.UploadBiz
	0, // 1: oss.v1.UploadCallbackResponse.Biz:type_name -> oss.v1.UploadBiz
	1, // 2: oss.v1.OSSService.SignUpload:input_type -> oss.v1.SignUploadRequest
	3, // 3: oss.v1.OSSService.UploadCallback:input_type -> oss.v1.UploadCallbackRequest
	5, // 4: oss.v1.OSSService.GetObjectURL:input_type -> oss.v1.GetObjectURLRequest
	7, // 5: oss.v1.OSSService.HealthCheck:input_type -> oss.v1.HealthCheckRequest
	2, // 6: oss.v1.OSSService.SignUpload:output_type -> oss.v1.SignUploadResponse
	4, // 7: oss.v1.OSSService.UploadCallback:output_type -> oss.v1.UploadCallbackResponse
	6, // 8: oss.v1.OSSService.GetObjectURL:output_type -> oss.v1.GetObjectURLResponse
	8, // 9: oss.v1.OSSService.HealthCheck:output_type -> oss.v1.HealthCheckResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_oss_v1_oss_proto_init() }
func file_api_proto_oss_v1_oss_proto_init() {
	if File_api_proto_oss_v1_oss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_oss_v1_oss_proto_rawDesc), len(file_api_proto_oss_v1_oss_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_oss_v1_oss_proto_goTypes,
		DependencyIndexes: file_api_proto_oss_v1_oss_proto_depIdxs,
		EnumInfos:         file_api_proto_oss_v1_oss_proto_enumTypes,
		MessageInfos:      file_api_proto_oss_v1_oss_proto_msgTypes,
	}.Build()
	File_api_proto_oss_v1_oss_proto = out.File
	file_api_proto_oss_v1_oss_proto_goTypes = nil
	file_api_proto_oss_v1_oss_proto_depIdxs = nil
}
