// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/oss/v1/oss.proto

package oss_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OSSService_SignUpload_FullMethodName     = "/oss.v1.OSSService/SignUpload"
	OSSService_UploadCallback_FullMethodName = "/oss.v1.OSSService/UploadCallback"
	OSSService_GetObjectURL_FullMethodName   = "/oss.v1.OSSService/GetObjectURL"
	OSSService_HealthCheck_FullMethodName    = "/oss.v1.OSSService/HealthCheck"
)

// OSSServiceClient is the client API for OSSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSSServiceClient interface {
	// 获取公共 OSS 上传签名
	SignUpload(ctx context.Context, in *SignUploadRequest, opts ...grpc.CallOption) (*SignUploadResponse, error)
	// 解析 OSS 上传回调对象, 业务服务负责后续落库/索引
	UploadCallback(ctx context.Context, in *UploadCallbackRequest, opts ...grpc.CallOption) (*UploadCallbackResponse, error)
	// 获取 OSS 对象下载预签名 URL
	GetObjectURL(ctx context.Context, in *GetObjectURLRequest, opts ...grpc.CallOption) (*GetObjectURLResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type oSSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOSSServiceClient(cc grpc.ClientConnInterface) OSSServiceClient {
	return &oSSServiceClient{cc}
}

func (c *oSSServiceClient) SignUpload(ctx context.Context, in *SignUploadRequest, opts ...grpc.CallOption) (*SignUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignUploadResponse)
	err := c.cc.Invoke(ctx, OSSService_SignUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSSServiceClient) UploadCallback(ctx context.Context, in *UploadCallbackRequest, opts ...grpc.CallOption) (*UploadCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadCallbackResponse)
	err := c.cc.Invoke(ctx, OSSService_UploadCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSSServiceClient) GetObjectURL(ctx context.Context, in *GetObjectURLRequest, opts ...grpc.CallOption) (*GetObjectURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectURLResponse)
	err := c.cc.Invoke(ctx, OSSService_GetObjectURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSSServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OSSService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSSServiceServer is the server API for OSSService service.
// All implementations must embed UnimplementedOSSServiceServer
// for forward compatibility.
type OSSServiceServer interface {
	// 获取公共 OSS 上传签名
	SignUpload(context.Context, *SignUploadRequest) (*SignUploadResponse, error)
	// 解析 OSS 上传回调对象, 业务服务负责后续落库/索引
	UploadCallback(context.Context, *UploadCallbackRequest) (*UploadCallbackResponse, error)
	// 获取 OSS 对象下载预签名 URL
	GetObjectURL(context.Context, *GetObjectURLRequest) (*GetObjectURLResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedOSSServiceServer()
}

// UnimplementedOSSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOSSServiceServer struct{}

func (UnimplementedOSSServiceServer) SignUpload(context.Context, *SignUploadRequest) (*SignUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignUpload not implemented")
}
func (UnimplementedOSSServiceServer) UploadCallback(context.Context, *UploadCallbackRequest) (*UploadCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadCallback not implemented")
}
func (UnimplementedOSSServiceServer) GetObjectURL(context.Context, *GetObjectURLRequest) (*GetObjectURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectURL not implemented")
}
func (UnimplementedOSSServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOSSServiceServer) mustEmbedUnimplementedOSSServiceServer() {}
func (UnimplementedOSSServiceServer) testEmbeddedByValue()                    {}

// UnsafeOSSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSSServiceServer will
// result in compilation errors.
type UnsafeOSSServiceServer interface {
	mustEmbedUnimplementedOSSServiceServer()
}

func RegisterOSSServiceServer(s grpc.ServiceRegistrar, srv OSSServiceServer) {
	// If the following call panics, it indicates UnimplementedOSSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OSSService_ServiceDesc, srv)
}

func _OSSService_SignUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServiceServer).SignUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSSService_SignUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServiceServer).SignUpload(ctx, req.(*SignUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSSService_UploadCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServiceServer).UploadCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSSService_UploadCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServiceServer).UploadCallback(ctx, req.(*UploadCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSSService_GetObjectURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServiceServer).GetObjectURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSSService_GetObjectURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServiceServer).GetObjectURL(ctx, req.(*GetObjectURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSSService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSSService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OSSService_ServiceDesc is the grpc.ServiceDesc for OSSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oss.v1.OSSService",
	HandlerType: (*OSSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUpload",
			Handler:    _OSSService_SignUpload_Handler,
		},
		{
			MethodName: "UploadCallback",
			Handler:    _OSSService_UploadCallback_Handler,
		},
		{
			MethodName: "GetObjectURL",
			Handler:    _OSSService_GetObjectURL_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OSSService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/oss/v1/oss.proto",
}
