// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/rank/v1/rank.proto

package rank_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankService_RankUser_FullMethodName     = "/rank.v1.RankService/RankUser"
	RankService_RankPost_FullMethodName     = "/rank.v1.RankService/RankPost"
	RankService_RankTopKUser_FullMethodName = "/rank.v1.RankService/RankTopKUser"
	RankService_RankTopKPost_FullMethodName = "/rank.v1.RankService/RankTopKPost"
	RankService_TopKUser_FullMethodName     = "/rank.v1.RankService/TopKUser"
	RankService_TopKPost_FullMethodName     = "/rank.v1.RankService/TopKPost"
	RankService_HealthCheck_FullMethodName  = "/rank.v1.RankService/HealthCheck"
)

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankServiceClient interface {
	// 计算用户分数
	RankUser(ctx context.Context, in *RankIDRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error)
	// 计算帖子分数
	RankPost(ctx context.Context, in *RankIDRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error)
	// 计算用户榜单
	RankTopKUser(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error)
	// 计算帖子榜单
	RankTopKPost(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error)
	// 返回用户榜单
	TopKUser(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*TopKUserResponse, error)
	// 返回帖子榜单
	TopKPost(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*TopKPostResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type rankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankServiceClient(cc grpc.ClientConnInterface) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) RankUser(ctx context.Context, in *RankIDRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankEmptyResponse)
	err := c.cc.Invoke(ctx, RankService_RankUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) RankPost(ctx context.Context, in *RankIDRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankEmptyResponse)
	err := c.cc.Invoke(ctx, RankService_RankPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) RankTopKUser(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankEmptyResponse)
	err := c.cc.Invoke(ctx, RankService_RankTopKUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) RankTopKPost(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*RankEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankEmptyResponse)
	err := c.cc.Invoke(ctx, RankService_RankTopKPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) TopKUser(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*TopKUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopKUserResponse)
	err := c.cc.Invoke(ctx, RankService_TopKUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) TopKPost(ctx context.Context, in *RankEmptyRequest, opts ...grpc.CallOption) (*TopKPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopKPostResponse)
	err := c.cc.Invoke(ctx, RankService_TopKPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RankService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServiceServer is the server API for RankService service.
// All implementations must embed UnimplementedRankServiceServer
// for forward compatibility.
type RankServiceServer interface {
	// 计算用户分数
	RankUser(context.Context, *RankIDRequest) (*RankEmptyResponse, error)
	// 计算帖子分数
	RankPost(context.Context, *RankIDRequest) (*RankEmptyResponse, error)
	// 计算用户榜单
	RankTopKUser(context.Context, *RankEmptyRequest) (*RankEmptyResponse, error)
	// 计算帖子榜单
	RankTopKPost(context.Context, *RankEmptyRequest) (*RankEmptyResponse, error)
	// 返回用户榜单
	TopKUser(context.Context, *RankEmptyRequest) (*TopKUserResponse, error)
	// 返回帖子榜单
	TopKPost(context.Context, *RankEmptyRequest) (*TopKPostResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRankServiceServer()
}

// UnimplementedRankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankServiceServer struct{}

func (UnimplementedRankServiceServer) RankUser(context.Context, *RankIDRequest) (*RankEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RankUser not implemented")
}
func (UnimplementedRankServiceServer) RankPost(context.Context, *RankIDRequest) (*RankEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RankPost not implemented")
}
func (UnimplementedRankServiceServer) RankTopKUser(context.Context, *RankEmptyRequest) (*RankEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RankTopKUser not implemented")
}
func (UnimplementedRankServiceServer) RankTopKPost(context.Context, *RankEmptyRequest) (*RankEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RankTopKPost not implemented")
}
func (UnimplementedRankServiceServer) TopKUser(context.Context, *RankEmptyRequest) (*TopKUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopKUser not implemented")
}
func (UnimplementedRankServiceServer) TopKPost(context.Context, *RankEmptyRequest) (*TopKPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopKPost not implemented")
}
func (UnimplementedRankServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRankServiceServer) mustEmbedUnimplementedRankServiceServer() {}
func (UnimplementedRankServiceServer) testEmbeddedByValue()                     {}

// UnsafeRankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServiceServer will
// result in compilation errors.
type UnsafeRankServiceServer interface {
	mustEmbedUnimplementedRankServiceServer()
}

func RegisterRankServiceServer(s grpc.ServiceRegistrar, srv RankServiceServer) {
	// If the following call panics, it indicates UnimplementedRankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankService_ServiceDesc, srv)
}

func _RankService_RankUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).RankUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_RankUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).RankUser(ctx, req.(*RankIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_RankPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).RankPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_RankPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).RankPost(ctx, req.(*RankIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_RankTopKUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).RankTopKUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_RankTopKUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).RankTopKUser(ctx, req.(*RankEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_RankTopKPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).RankTopKPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_RankTopKPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).RankTopKPost(ctx, req.(*RankEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_TopKUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).TopKUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_TopKUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).TopKUser(ctx, req.(*RankEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_TopKPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).TopKPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_TopKPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).TopKPost(ctx, req.(*RankEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankService_ServiceDesc is the grpc.ServiceDesc for RankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rank.v1.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RankUser",
			Handler:    _RankService_RankUser_Handler,
		},
		{
			MethodName: "RankPost",
			Handler:    _RankService_RankPost_Handler,
		},
		{
			MethodName: "RankTopKUser",
			Handler:    _RankService_RankTopKUser_Handler,
		},
		{
			MethodName: "RankTopKPost",
			Handler:    _RankService_RankTopKPost_Handler,
		},
		{
			MethodName: "TopKUser",
			Handler:    _RankService_TopKUser_Handler,
		},
		{
			MethodName: "TopKPost",
			Handler:    _RankService_TopKPost_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RankService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rank/v1/rank.proto",
}
