// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/rank/v1/rank.proto

package rank_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankIDRequest) Reset() {
	*x = RankIDRequest{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankIDRequest) ProtoMessage() {}

func (x *RankIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankIDRequest.ProtoReflect.Descriptor instead.
func (*RankIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{0}
}

func (x *RankIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RankEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankEmptyRequest) Reset() {
	*x = RankEmptyRequest{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankEmptyRequest) ProtoMessage() {}

func (x *RankEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankEmptyRequest.ProtoReflect.Descriptor instead.
func (*RankEmptyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{1}
}

type RankEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankEmptyResponse) Reset() {
	*x = RankEmptyResponse{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankEmptyResponse) ProtoMessage() {}

func (x *RankEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankEmptyResponse.ProtoReflect.Descriptor instead.
func (*RankEmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{2}
}

type RankUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankUser) Reset() {
	*x = RankUser{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankUser) ProtoMessage() {}

func (x *RankUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankUser.ProtoReflect.Descriptor instead.
func (*RankUser) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{3}
}

func (x *RankUser) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RankUser) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankPost) Reset() {
	*x = RankPost{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPost) ProtoMessage() {}

func (x *RankPost) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPost.ProtoReflect.Descriptor instead.
func (*RankPost) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{4}
}

func (x *RankPost) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RankPost) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TopKUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*RankUser            `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopKUserResponse) Reset() {
	*x = TopKUserResponse{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopKUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopKUserResponse) ProtoMessage() {}

func (x *TopKUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopKUserResponse.ProtoReflect.Descriptor instead.
func (*TopKUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{5}
}

func (x *TopKUserResponse) GetUsers() []*RankUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type TopKPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*RankPost            `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopKPostResponse) Reset() {
	*x = TopKPostResponse{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopKPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopKPostResponse) ProtoMessage() {}

func (x *TopKPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopKPostResponse.ProtoReflect.Descriptor instead.
func (*TopKPostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{6}
}

func (x *TopKPostResponse) GetPosts() []*RankPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_v1_rank_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_v1_rank_proto_rawDescGZIP(), []int{8}
}

var File_api_proto_rank_v1_rank_proto protoreflect.FileDescriptor

const file_api_proto_rank_v1_rank_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/rank/v1/rank.proto\x12\arank.v1\"\x1f\n" +
	"\rRankIDRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"\x12\n" +
	"\x10RankEmptyRequest\"\x13\n" +
	"\x11RankEmptyResponse\"0\n" +
	"\bRankUser\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Score\x18\x02 \x01(\x03R\x05Score\"0\n" +
	"\bRankPost\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Score\x18\x02 \x01(\x03R\x05Score\";\n" +
	"\x10TopKUserResponse\x12'\n" +
	"\x05Users\x18\x01 \x03(\v2\x11.rank.v1.RankUserR\x05Users\";\n" +
	"\x10TopKPostResponse\x12'\n" +
	"\x05Posts\x18\x01 \x03(\v2\x11.rank.v1.RankPostR\x05Posts\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xe9\x03\n" +
	"\vRankService\x12>\n" +
	"\bRankUser\x12\x16.rank.v1.RankIDRequest\x1a\x1a.rank.v1.RankEmptyResponse\x12>\n" +
	"\bRankPost\x12\x16.rank.v1.RankIDRequest\x1a\x1a.rank.v1.RankEmptyResponse\x12E\n" +
	"\fRankTopKUser\x12\x19.rank.v1.RankEmptyRequest\x1a\x1a.rank.v1.RankEmptyResponse\x12E\n" +
	"\fRankTopKPost\x12\x19.rank.v1.RankEmptyRequest\x1a\x1a.rank.v1.RankEmptyResponse\x12@\n" +
	"\bTopKUser\x12\x19.rank.v1.RankEmptyRequest\x1a\x19.rank.v1.TopKUserResponse\x12@\n" +
	"\bTopKPost\x12\x19.rank.v1.RankEmptyRequest\x1a\x19.rank.v1.TopKPostResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.rank.v1.HealthCheckRequest\x1a\x1c.rank.v1.HealthCheckResponseB<Z:github.com/yzletter/go-postery/api/proto/rank/v1;rank_grpcb\x06proto3"

var (
	file_api_proto_rank_v1_rank_proto_rawDescOnce sync.Once
	file_api_proto_rank_v1_rank_proto_rawDescData []byte
)

func file_api_proto_rank_v1_rank_proto_rawDescGZIP() []byte {
	file_api_proto_rank_v1_rank_proto_rawDescOnce.Do(func() {
		file_api_proto_rank_v1_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rank_v1_rank_proto_rawDesc), len(file_api_proto_rank_v1_rank_proto_rawDesc)))
	})
	return file_api_proto_rank_v1_rank_proto_rawDescData
}

var file_api_proto_rank_v1_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_rank_v1_rank_proto_goTypes = []any{
	(*RankIDRequest)(nil),       // 0: rank.v1.RankIDRequest
	(*RankEmptyRequest)(nil),    // 1: rank.v1.RankEmptyRequest
	(*RankEmptyResponse)(nil),   // 2: rank.v1.RankEmptyResponse
	(*RankUser)(nil),            // 3: rank.v1.RankUser
	(*RankPost)(nil),            // 4: rank.v1.RankPost
	(*TopKUserResponse)(nil),    // 5: rank.v1.TopKUserResponse
	(*TopKPostResponse)(nil),    // 6: rank.v1.TopKPostResponse
	(*HealthCheckRequest)(nil),  // 7: rank.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 8: rank.v1.HealthCheckResponse
}
var file_api_proto_rank_v1_rank_proto_depIdxs = []int32{
	3, // 0: rank.v1.TopKUserResponse.Users:type_name -> rank.v1.RankUser
	4, // 1: rank.v1.TopKPostResponse.Posts:type_name -> rank.v1.RankPost
	0, // 2: rank.v1.RankService.RankUser:input_type -> rank.v1.RankIDRequest
	0, // 3: rank.v1.RankService.RankPost:input_type -> rank.v1.RankIDRequest
	1, // 4: rank.v1.RankService.RankTopKUser:input_type -> rank.v1.RankEmptyRequest
	1, // 5: rank.v1.RankService.RankTopKPost:input_type -> rank.v1.RankEmptyRequest
	1, // 6: rank.v1.RankService.TopKUser:input_type -> rank.v1.RankEmptyRequest
	1, // 7: rank.v1.RankService.TopKPost:input_type -> rank.v1.RankEmptyRequest
	7, // 8: rank.v1.RankService.HealthCheck:input_type -> rank.v1.HealthCheckRequest
	2, // 9: rank.v1.RankService.RankUser:output_type -> rank.v1.RankEmptyResponse
	2, // 10: rank.v1.RankService.RankPost:output_type -> rank.v1.RankEmptyResponse
	2, // 11: rank.v1.RankService.RankTopKUser:output_type -> rank.v1.RankEmptyResponse
	2, // 12: rank.v1.RankService.RankTopKPost:output_type -> rank.v1.RankEmptyResponse
	5, // 13: rank.v1.RankService.TopKUser:output_type -> rank.v1.TopKUserResponse
	6, // 14: rank.v1.RankService.TopKPost:output_type -> rank.v1.TopKPostResponse
	8, // 15: rank.v1.RankService.HealthCheck:output_type -> rank.v1.HealthCheckResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_rank_v1_rank_proto_init() }
func file_api_proto_rank_v1_rank_proto_init() {
	if File_api_proto_rank_v1_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rank_v1_rank_proto_rawDesc), len(file_api_proto_rank_v1_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rank_v1_rank_proto_goTypes,
		DependencyIndexes: file_api_proto_rank_v1_rank_proto_depIdxs,
		MessageInfos:      file_api_proto_rank_v1_rank_proto_msgTypes,
	}.Build()
	File_api_proto_rank_v1_rank_proto = out.File
	file_api_proto_rank_v1_rank_proto_goTypes = nil
	file_api_proto_rank_v1_rank_proto_depIdxs = nil
}
