// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/interview/v1/interview.proto

package interview_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterviewService_Chat_FullMethodName                    = "/interview.v1.InterviewService/Chat"
	InterviewService_StartInterview_FullMethodName          = "/interview.v1.InterviewService/StartInterview"
	InterviewService_Answer_FullMethodName                  = "/interview.v1.InterviewService/Answer"
	InterviewService_UploadQuestionsSign_FullMethodName     = "/interview.v1.InterviewService/UploadQuestionsSign"
	InterviewService_UploadQuestionsCallback_FullMethodName = "/interview.v1.InterviewService/UploadQuestionsCallback"
	InterviewService_UploadQuestions_FullMethodName         = "/interview.v1.InterviewService/UploadQuestions"
	InterviewService_QuitInterview_FullMethodName           = "/interview.v1.InterviewService/QuitInterview"
	InterviewService_Evaluation_FullMethodName              = "/interview.v1.InterviewService/Evaluation"
	InterviewService_HealthCheck_FullMethodName             = "/interview.v1.InterviewService/HealthCheck"
)

// InterviewServiceClient is the client API for InterviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterviewServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	StartInterview(ctx context.Context, in *StartInterviewRequest, opts ...grpc.CallOption) (*StartInterviewResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
	UploadQuestionsSign(ctx context.Context, in *UploadQuestionsSignRequest, opts ...grpc.CallOption) (*UploadQuestionsSignResponse, error)
	UploadQuestionsCallback(ctx context.Context, in *UploadQuestionsCallbackRequest, opts ...grpc.CallOption) (*UploadQuestionsCallbackResponse, error)
	UploadQuestions(ctx context.Context, in *UploadQuestionsRequest, opts ...grpc.CallOption) (*UploadQuestionsResponse, error)
	QuitInterview(ctx context.Context, in *QuitInterviewRequest, opts ...grpc.CallOption) (*QuitInterviewResponse, error)
	Evaluation(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type interviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterviewServiceClient(cc grpc.ClientConnInterface) InterviewServiceClient {
	return &interviewServiceClient{cc}
}

func (c *interviewServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, InterviewService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) StartInterview(ctx context.Context, in *StartInterviewRequest, opts ...grpc.CallOption) (*StartInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInterviewResponse)
	err := c.cc.Invoke(ctx, InterviewService_StartInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, InterviewService_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) UploadQuestionsSign(ctx context.Context, in *UploadQuestionsSignRequest, opts ...grpc.CallOption) (*UploadQuestionsSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadQuestionsSignResponse)
	err := c.cc.Invoke(ctx, InterviewService_UploadQuestionsSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) UploadQuestionsCallback(ctx context.Context, in *UploadQuestionsCallbackRequest, opts ...grpc.CallOption) (*UploadQuestionsCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadQuestionsCallbackResponse)
	err := c.cc.Invoke(ctx, InterviewService_UploadQuestionsCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) UploadQuestions(ctx context.Context, in *UploadQuestionsRequest, opts ...grpc.CallOption) (*UploadQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadQuestionsResponse)
	err := c.cc.Invoke(ctx, InterviewService_UploadQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) QuitInterview(ctx context.Context, in *QuitInterviewRequest, opts ...grpc.CallOption) (*QuitInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuitInterviewResponse)
	err := c.cc.Invoke(ctx, InterviewService_QuitInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) Evaluation(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationResponse)
	err := c.cc.Invoke(ctx, InterviewService_Evaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InterviewService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterviewServiceServer is the server API for InterviewService service.
// All implementations must embed UnimplementedInterviewServiceServer
// for forward compatibility.
type InterviewServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	StartInterview(context.Context, *StartInterviewRequest) (*StartInterviewResponse, error)
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	UploadQuestionsSign(context.Context, *UploadQuestionsSignRequest) (*UploadQuestionsSignResponse, error)
	UploadQuestionsCallback(context.Context, *UploadQuestionsCallbackRequest) (*UploadQuestionsCallbackResponse, error)
	UploadQuestions(context.Context, *UploadQuestionsRequest) (*UploadQuestionsResponse, error)
	QuitInterview(context.Context, *QuitInterviewRequest) (*QuitInterviewResponse, error)
	Evaluation(context.Context, *EvaluationRequest) (*EvaluationResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedInterviewServiceServer()
}

// UnimplementedInterviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterviewServiceServer struct{}

func (UnimplementedInterviewServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedInterviewServiceServer) StartInterview(context.Context, *StartInterviewRequest) (*StartInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInterview not implemented")
}
func (UnimplementedInterviewServiceServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedInterviewServiceServer) UploadQuestionsSign(context.Context, *UploadQuestionsSignRequest) (*UploadQuestionsSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadQuestionsSign not implemented")
}
func (UnimplementedInterviewServiceServer) UploadQuestionsCallback(context.Context, *UploadQuestionsCallbackRequest) (*UploadQuestionsCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadQuestionsCallback not implemented")
}
func (UnimplementedInterviewServiceServer) UploadQuestions(context.Context, *UploadQuestionsRequest) (*UploadQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadQuestions not implemented")
}
func (UnimplementedInterviewServiceServer) QuitInterview(context.Context, *QuitInterviewRequest) (*QuitInterviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuitInterview not implemented")
}
func (UnimplementedInterviewServiceServer) Evaluation(context.Context, *EvaluationRequest) (*EvaluationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluation not implemented")
}
func (UnimplementedInterviewServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInterviewServiceServer) mustEmbedUnimplementedInterviewServiceServer() {}
func (UnimplementedInterviewServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterviewServiceServer will
// result in compilation errors.
type UnsafeInterviewServiceServer interface {
	mustEmbedUnimplementedInterviewServiceServer()
}

func RegisterInterviewServiceServer(s grpc.ServiceRegistrar, srv InterviewServiceServer) {
	// If the following call panics, it indicates UnimplementedInterviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterviewService_ServiceDesc, srv)
}

func _InterviewService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_StartInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).StartInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_StartInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).StartInterview(ctx, req.(*StartInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_UploadQuestionsSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadQuestionsSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).UploadQuestionsSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_UploadQuestionsSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).UploadQuestionsSign(ctx, req.(*UploadQuestionsSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_UploadQuestionsCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadQuestionsCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).UploadQuestionsCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_UploadQuestionsCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).UploadQuestionsCallback(ctx, req.(*UploadQuestionsCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_UploadQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).UploadQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_UploadQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).UploadQuestions(ctx, req.(*UploadQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_QuitInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).QuitInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_QuitInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).QuitInterview(ctx, req.(*QuitInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_Evaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).Evaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_Evaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).Evaluation(ctx, req.(*EvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterviewService_ServiceDesc is the grpc.ServiceDesc for InterviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.v1.InterviewService",
	HandlerType: (*InterviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _InterviewService_Chat_Handler,
		},
		{
			MethodName: "StartInterview",
			Handler:    _InterviewService_StartInterview_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _InterviewService_Answer_Handler,
		},
		{
			MethodName: "UploadQuestionsSign",
			Handler:    _InterviewService_UploadQuestionsSign_Handler,
		},
		{
			MethodName: "UploadQuestionsCallback",
			Handler:    _InterviewService_UploadQuestionsCallback_Handler,
		},
		{
			MethodName: "UploadQuestions",
			Handler:    _InterviewService_UploadQuestions_Handler,
		},
		{
			MethodName: "QuitInterview",
			Handler:    _InterviewService_QuitInterview_Handler,
		},
		{
			MethodName: "Evaluation",
			Handler:    _InterviewService_Evaluation_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InterviewService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/interview/v1/interview.proto",
}
