// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/interview/v1/interview.proto

package interview_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID     int64                  `protobuf:"varint,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=Input,proto3" json:"Input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ChatRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *ChatRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StartInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	JD            string                 `protobuf:"bytes,2,opt,name=JD,proto3" json:"JD,omitempty"`
	Resume        string                 `protobuf:"bytes,3,opt,name=Resume,proto3" json:"Resume,omitempty"`
	CandidateName string                 `protobuf:"bytes,4,opt,name=CandidateName,proto3" json:"CandidateName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInterviewRequest) Reset() {
	*x = StartInterviewRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInterviewRequest) ProtoMessage() {}

func (x *StartInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInterviewRequest.ProtoReflect.Descriptor instead.
func (*StartInterviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{2}
}

func (x *StartInterviewRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *StartInterviewRequest) GetJD() string {
	if x != nil {
		return x.JD
	}
	return ""
}

func (x *StartInterviewRequest) GetResume() string {
	if x != nil {
		return x.Resume
	}
	return ""
}

func (x *StartInterviewRequest) GetCandidateName() string {
	if x != nil {
		return x.CandidateName
	}
	return ""
}

type StartInterviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInterviewResponse) Reset() {
	*x = StartInterviewResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInterviewResponse) ProtoMessage() {}

func (x *StartInterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInterviewResponse.ProtoReflect.Descriptor instead.
func (*StartInterviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{3}
}

func (x *StartInterviewResponse) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID     int64                  `protobuf:"varint,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AnswerRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *AnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{5}
}

type UploadQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SourceFile    string                 `protobuf:"bytes,2,opt,name=SourceFile,proto3" json:"SourceFile,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsRequest) Reset() {
	*x = UploadQuestionsRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsRequest) ProtoMessage() {}

func (x *UploadQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsRequest.ProtoReflect.Descriptor instead.
func (*UploadQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{6}
}

func (x *UploadQuestionsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UploadQuestionsRequest) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *UploadQuestionsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsResponse) Reset() {
	*x = UploadQuestionsResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsResponse) ProtoMessage() {}

func (x *UploadQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsResponse.ProtoReflect.Descriptor instead.
func (*UploadQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{7}
}

type UploadQuestionsSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsSignRequest) Reset() {
	*x = UploadQuestionsSignRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsSignRequest) ProtoMessage() {}

func (x *UploadQuestionsSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsSignRequest.ProtoReflect.Descriptor instead.
func (*UploadQuestionsSignRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{8}
}

func (x *UploadQuestionsSignRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type UploadQuestionsSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsSignResponse) Reset() {
	*x = UploadQuestionsSignResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsSignResponse) ProtoMessage() {}

func (x *UploadQuestionsSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsSignResponse.ProtoReflect.Descriptor instead.
func (*UploadQuestionsSignResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{9}
}

func (x *UploadQuestionsSignResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type UploadQuestionsCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsCallbackRequest) Reset() {
	*x = UploadQuestionsCallbackRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsCallbackRequest) ProtoMessage() {}

func (x *UploadQuestionsCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsCallbackRequest.ProtoReflect.Descriptor instead.
func (*UploadQuestionsCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{10}
}

func (x *UploadQuestionsCallbackRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UploadQuestionsCallbackRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type UploadQuestionsCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadQuestionsCallbackResponse) Reset() {
	*x = UploadQuestionsCallbackResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadQuestionsCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadQuestionsCallbackResponse) ProtoMessage() {}

func (x *UploadQuestionsCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadQuestionsCallbackResponse.ProtoReflect.Descriptor instead.
func (*UploadQuestionsCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{11}
}

type QuitInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID     int64                  `protobuf:"varint,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitInterviewRequest) Reset() {
	*x = QuitInterviewRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitInterviewRequest) ProtoMessage() {}

func (x *QuitInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitInterviewRequest.ProtoReflect.Descriptor instead.
func (*QuitInterviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{12}
}

func (x *QuitInterviewRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QuitInterviewRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type QuitInterviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitInterviewResponse) Reset() {
	*x = QuitInterviewResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitInterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitInterviewResponse) ProtoMessage() {}

func (x *QuitInterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitInterviewResponse.ProtoReflect.Descriptor instead.
func (*QuitInterviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{13}
}

type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID     int64                  `protobuf:"varint,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluationRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *EvaluationRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{15}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{16}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interview_v1_interview_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interview_v1_interview_proto_rawDescGZIP(), []int{17}
}

var File_api_proto_interview_v1_interview_proto protoreflect.FileDescriptor

const file_api_proto_interview_v1_interview_proto_rawDesc = "" +
	"\n" +
	"&api/proto/interview/v1/interview.proto\x12\finterview.v1\"Y\n" +
	"\vChatRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tSessionID\x18\x02 \x01(\x03R\tSessionID\x12\x14\n" +
	"\x05Input\x18\x03 \x01(\tR\x05Input\"F\n" +
	"\fChatResponse\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\"}\n" +
	"\x15StartInterviewRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x0e\n" +
	"\x02JD\x18\x02 \x01(\tR\x02JD\x12\x16\n" +
	"\x06Resume\x18\x03 \x01(\tR\x06Resume\x12$\n" +
	"\rCandidateName\x18\x04 \x01(\tR\rCandidateName\"6\n" +
	"\x16StartInterviewResponse\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\"]\n" +
	"\rAnswerRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tSessionID\x18\x02 \x01(\x03R\tSessionID\x12\x16\n" +
	"\x06Answer\x18\x03 \x01(\tR\x06Answer\"\x10\n" +
	"\x0eAnswerResponse\"d\n" +
	"\x16UploadQuestionsRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"SourceFile\x18\x02 \x01(\tR\n" +
	"SourceFile\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\"\x19\n" +
	"\x17UploadQuestionsResponse\"4\n" +
	"\x1aUploadQuestionsSignRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\"9\n" +
	"\x1bUploadQuestionsSignResponse\x12\x1a\n" +
	"\bResponse\x18\x01 \x01(\tR\bResponse\"X\n" +
	"\x1eUploadQuestionsCallbackRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"ObjectName\x18\x02 \x01(\tR\n" +
	"ObjectName\"!\n" +
	"\x1fUploadQuestionsCallbackResponse\"L\n" +
	"\x14QuitInterviewRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tSessionID\x18\x02 \x01(\x03R\tSessionID\"\x17\n" +
	"\x15QuitInterviewResponse\"I\n" +
	"\x11EvaluationRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tSessionID\x18\x02 \x01(\x03R\tSessionID\"\x14\n" +
	"\x12EvaluationResponse\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xb6\x06\n" +
	"\x10InterviewService\x12=\n" +
	"\x04Chat\x12\x19.interview.v1.ChatRequest\x1a\x1a.interview.v1.ChatResponse\x12[\n" +
	"\x0eStartInterview\x12#.interview.v1.StartInterviewRequest\x1a$.interview.v1.StartInterviewResponse\x12C\n" +
	"\x06Answer\x12\x1b.interview.v1.AnswerRequest\x1a\x1c.interview.v1.AnswerResponse\x12j\n" +
	"\x13UploadQuestionsSign\x12(.interview.v1.UploadQuestionsSignRequest\x1a).interview.v1.UploadQuestionsSignResponse\x12v\n" +
	"\x17UploadQuestionsCallback\x12,.interview.v1.UploadQuestionsCallbackRequest\x1a-.interview.v1.UploadQuestionsCallbackResponse\x12^\n" +
	"\x0fUploadQuestions\x12$.interview.v1.UploadQuestionsRequest\x1a%.interview.v1.UploadQuestionsResponse\x12X\n" +
	"\rQuitInterview\x12\".interview.v1.QuitInterviewRequest\x1a#.interview.v1.QuitInterviewResponse\x12O\n" +
	"\n" +
	"Evaluation\x12\x1f.interview.v1.EvaluationRequest\x1a .interview.v1.EvaluationResponse\x12R\n" +
	"\vHealthCheck\x12 .interview.v1.HealthCheckRequest\x1a!.interview.v1.HealthCheckResponseBFZDgithub.com/yzletter/go-postery/api/proto/interview/v1;interview_grpcb\x06proto3"

var (
	file_api_proto_interview_v1_interview_proto_rawDescOnce sync.Once
	file_api_proto_interview_v1_interview_proto_rawDescData []byte
)

func file_api_proto_interview_v1_interview_proto_rawDescGZIP() []byte {
	file_api_proto_interview_v1_interview_proto_rawDescOnce.Do(func() {
		file_api_proto_interview_v1_interview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_interview_v1_interview_proto_rawDesc), len(file_api_proto_interview_v1_interview_proto_rawDesc)))
	})
	return file_api_proto_interview_v1_interview_proto_rawDescData
}

var file_api_proto_interview_v1_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_interview_v1_interview_proto_goTypes = []any{
	(*ChatRequest)(nil),                     // 0: interview.v1.ChatRequest
	(*ChatResponse)(nil),                    // 1: interview.v1.ChatResponse
	(*StartInterviewRequest)(nil),           // 2: interview.v1.StartInterviewRequest
	(*StartInterviewResponse)(nil),          // 3: interview.v1.StartInterviewResponse
	(*AnswerRequest)(nil),                   // 4: interview.v1.AnswerRequest
	(*AnswerResponse)(nil),                  // 5: interview.v1.AnswerResponse
	(*UploadQuestionsRequest)(nil),          // 6: interview.v1.UploadQuestionsRequest
	(*UploadQuestionsResponse)(nil),         // 7: interview.v1.UploadQuestionsResponse
	(*UploadQuestionsSignRequest)(nil),      // 8: interview.v1.UploadQuestionsSignRequest
	(*UploadQuestionsSignResponse)(nil),     // 9: interview.v1.UploadQuestionsSignResponse
	(*UploadQuestionsCallbackRequest)(nil),  // 10: interview.v1.UploadQuestionsCallbackRequest
	(*UploadQuestionsCallbackResponse)(nil), // 11: interview.v1.UploadQuestionsCallbackResponse
	(*QuitInterviewRequest)(nil),            // 12: interview.v1.QuitInterviewRequest
	(*QuitInterviewResponse)(nil),           // 13: interview.v1.QuitInterviewResponse
	(*EvaluationRequest)(nil),               // 14: interview.v1.EvaluationRequest
	(*EvaluationResponse)(nil),              // 15: interview.v1.EvaluationResponse
	(*HealthCheckRequest)(nil),              // 16: interview.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 17: interview.v1.HealthCheckResponse
}
var file_api_proto_interview_v1_interview_proto_depIdxs = []int32{
	0,  // 0: interview.v1.InterviewService.Chat:input_type -> interview.v1.ChatRequest
	2,  // 1: interview.v1.InterviewService.StartInterview:input_type -> interview.v1.StartInterviewRequest
	4,  // 2: interview.v1.InterviewService.Answer:input_type -> interview.v1.AnswerRequest
	8,  // 3: interview.v1.InterviewService.UploadQuestionsSign:input_type -> interview.v1.UploadQuestionsSignRequest
	10, // 4: interview.v1.InterviewService.UploadQuestionsCallback:input_type -> interview.v1.UploadQuestionsCallbackRequest
	6,  // 5: interview.v1.InterviewService.UploadQuestions:input_type -> interview.v1.UploadQuestionsRequest
	12, // 6: interview.v1.InterviewService.QuitInterview:input_type -> interview.v1.QuitInterviewRequest
	14, // 7: interview.v1.InterviewService.Evaluation:input_type -> interview.v1.EvaluationRequest
	16, // 8: interview.v1.InterviewService.HealthCheck:input_type -> interview.v1.HealthCheckRequest
	1,  // 9: interview.v1.InterviewService.Chat:output_type -> interview.v1.ChatResponse
	3,  // 10: interview.v1.InterviewService.StartInterview:output_type -> interview.v1.StartInterviewResponse
	5,  // 11: interview.v1.InterviewService.Answer:output_type -> interview.v1.AnswerResponse
	9,  // 12: interview.v1.InterviewService.UploadQuestionsSign:output_type -> interview.v1.UploadQuestionsSignResponse
	11, // 13: interview.v1.InterviewService.UploadQuestionsCallback:output_type -> interview.v1.UploadQuestionsCallbackResponse
	7,  // 14: interview.v1.InterviewService.UploadQuestions:output_type -> interview.v1.UploadQuestionsResponse
	13, // 15: interview.v1.InterviewService.QuitInterview:output_type -> interview.v1.QuitInterviewResponse
	15, // 16: interview.v1.InterviewService.Evaluation:output_type -> interview.v1.EvaluationResponse
	17, // 17: interview.v1.InterviewService.HealthCheck:output_type -> interview.v1.HealthCheckResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_interview_v1_interview_proto_init() }
func file_api_proto_interview_v1_interview_proto_init() {
	if File_api_proto_interview_v1_interview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_interview_v1_interview_proto_rawDesc), len(file_api_proto_interview_v1_interview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_interview_v1_interview_proto_goTypes,
		DependencyIndexes: file_api_proto_interview_v1_interview_proto_depIdxs,
		MessageInfos:      file_api_proto_interview_v1_interview_proto_msgTypes,
	}.Build()
	File_api_proto_interview_v1_interview_proto = out.File
	file_api_proto_interview_v1_interview_proto_goTypes = nil
	file_api_proto_interview_v1_interview_proto_depIdxs = nil
}
