// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/code/v1/code.proto

package code_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送验证码请求体
type SendCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           int64                  `protobuf:"varint,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRequest) Reset() {
	*x = SendCodeRequest{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRequest) ProtoMessage() {}

func (x *SendCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRequest.ProtoReflect.Descriptor instead.
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{0}
}

func (x *SendCodeRequest) GetBiz() int64 {
	if x != nil {
		return x.Biz
	}
	return 0
}

func (x *SendCodeRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// 发送验证码响应体
type SendCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeResponse) Reset() {
	*x = SendCodeResponse{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResponse) ProtoMessage() {}

func (x *SendCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResponse.ProtoReflect.Descriptor instead.
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{1}
}

// 校验验证码请求体
type CheckCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           int64                  `protobuf:"varint,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeRequest) Reset() {
	*x = CheckCodeRequest{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeRequest) ProtoMessage() {}

func (x *CheckCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeRequest.ProtoReflect.Descriptor instead.
func (*CheckCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{2}
}

func (x *CheckCodeRequest) GetBiz() int64 {
	if x != nil {
		return x.Biz
	}
	return 0
}

func (x *CheckCodeRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CheckCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 校验验证码响应体
type CheckCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeResponse) Reset() {
	*x = CheckCodeResponse{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeResponse) ProtoMessage() {}

func (x *CheckCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeResponse.ProtoReflect.Descriptor instead.
func (*CheckCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{3}
}

func (x *CheckCodeResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_code_v1_code_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_code_v1_code_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_code_v1_code_proto_rawDescGZIP(), []int{5}
}

var File_api_proto_code_v1_code_proto protoreflect.FileDescriptor

const file_api_proto_code_v1_code_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/code/v1/code.proto\x12\acode.v1\"C\n" +
	"\x0fSendCodeRequest\x12\x10\n" +
	"\x03biz\x18\x01 \x01(\x03R\x03biz\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"\x12\n" +
	"\x10SendCodeResponse\"X\n" +
	"\x10CheckCodeRequest\x12\x10\n" +
	"\x03biz\x18\x01 \x01(\x03R\x03biz\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"+\n" +
	"\x11CheckCodeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xd5\x01\n" +
	"\vCodeService\x12;\n" +
	"\x04Send\x12\x18.code.v1.SendCodeRequest\x1a\x19.code.v1.SendCodeResponse\x12?\n" +
	"\x06Verify\x12\x19.code.v1.CheckCodeRequest\x1a\x1a.code.v1.CheckCodeResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.code.v1.HealthCheckRequest\x1a\x1c.code.v1.HealthCheckResponseB<Z:github.com/yzletter/go-postery/api/proto/code/v1;code_grpcb\x06proto3"

var (
	file_api_proto_code_v1_code_proto_rawDescOnce sync.Once
	file_api_proto_code_v1_code_proto_rawDescData []byte
)

func file_api_proto_code_v1_code_proto_rawDescGZIP() []byte {
	file_api_proto_code_v1_code_proto_rawDescOnce.Do(func() {
		file_api_proto_code_v1_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_code_v1_code_proto_rawDesc), len(file_api_proto_code_v1_code_proto_rawDesc)))
	})
	return file_api_proto_code_v1_code_proto_rawDescData
}

var file_api_proto_code_v1_code_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_code_v1_code_proto_goTypes = []any{
	(*SendCodeRequest)(nil),     // 0: code.v1.SendCodeRequest
	(*SendCodeResponse)(nil),    // 1: code.v1.SendCodeResponse
	(*CheckCodeRequest)(nil),    // 2: code.v1.CheckCodeRequest
	(*CheckCodeResponse)(nil),   // 3: code.v1.CheckCodeResponse
	(*HealthCheckRequest)(nil),  // 4: code.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: code.v1.HealthCheckResponse
}
var file_api_proto_code_v1_code_proto_depIdxs = []int32{
	0, // 0: code.v1.CodeService.Send:input_type -> code.v1.SendCodeRequest
	2, // 1: code.v1.CodeService.Verify:input_type -> code.v1.CheckCodeRequest
	4, // 2: code.v1.CodeService.HealthCheck:input_type -> code.v1.HealthCheckRequest
	1, // 3: code.v1.CodeService.Send:output_type -> code.v1.SendCodeResponse
	3, // 4: code.v1.CodeService.Verify:output_type -> code.v1.CheckCodeResponse
	5, // 5: code.v1.CodeService.HealthCheck:output_type -> code.v1.HealthCheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_code_v1_code_proto_init() }
func file_api_proto_code_v1_code_proto_init() {
	if File_api_proto_code_v1_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_code_v1_code_proto_rawDesc), len(file_api_proto_code_v1_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_code_v1_code_proto_goTypes,
		DependencyIndexes: file_api_proto_code_v1_code_proto_depIdxs,
		MessageInfos:      file_api_proto_code_v1_code_proto_msgTypes,
	}.Build()
	File_api_proto_code_v1_code_proto = out.File
	file_api_proto_code_v1_code_proto_goTypes = nil
	file_api_proto_code_v1_code_proto_depIdxs = nil
}
