// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/interactive/v1/interactive.proto

package interactive_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInteractive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadCnt       int64                  `protobuf:"varint,1,opt,name=ReadCnt,proto3" json:"ReadCnt,omitempty"`
	LikeCnt       int64                  `protobuf:"varint,2,opt,name=LikeCnt,proto3" json:"LikeCnt,omitempty"`
	CommentCnt    int64                  `protobuf:"varint,3,opt,name=CommentCnt,proto3" json:"CommentCnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInteractive) Reset() {
	*x = PostInteractive{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInteractive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInteractive) ProtoMessage() {}

func (x *PostInteractive) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInteractive.ProtoReflect.Descriptor instead.
func (*PostInteractive) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{0}
}

func (x *PostInteractive) GetReadCnt() int64 {
	if x != nil {
		return x.ReadCnt
	}
	return 0
}

func (x *PostInteractive) GetLikeCnt() int64 {
	if x != nil {
		return x.LikeCnt
	}
	return 0
}

func (x *PostInteractive) GetCommentCnt() int64 {
	if x != nil {
		return x.CommentCnt
	}
	return 0
}

type UserInteractive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowCnt     int64                  `protobuf:"varint,1,opt,name=FollowCnt,proto3" json:"FollowCnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInteractive) Reset() {
	*x = UserInteractive{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInteractive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInteractive) ProtoMessage() {}

func (x *UserInteractive) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInteractive.ProtoReflect.Descriptor instead.
func (*UserInteractive) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{1}
}

func (x *UserInteractive) GetFollowCnt() int64 {
	if x != nil {
		return x.FollowCnt
	}
	return 0
}

type PostIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostIDRequest) Reset() {
	*x = PostIDRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostIDRequest) ProtoMessage() {}

func (x *PostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostIDRequest.ProtoReflect.Descriptor instead.
func (*PostIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{2}
}

func (x *PostIDRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{3}
}

func (x *UserIDRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PostID        int64                  `protobuf:"varint,2,opt,name=PostID,proto3" json:"PostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{4}
}

func (x *LikeRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LikeRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerID    int64                  `protobuf:"varint,1,opt,name=FollowerID,proto3" json:"FollowerID,omitempty"`
	FolloweeID    int64                  `protobuf:"varint,2,opt,name=FolloweeID,proto3" json:"FolloweeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{5}
}

func (x *FollowRequest) GetFollowerID() int64 {
	if x != nil {
		return x.FollowerID
	}
	return 0
}

func (x *FollowRequest) GetFolloweeID() int64 {
	if x != nil {
		return x.FolloweeID
	}
	return 0
}

type IfFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfFollowResponse) Reset() {
	*x = IfFollowResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfFollowResponse) ProtoMessage() {}

func (x *IfFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfFollowResponse.ProtoReflect.Descriptor instead.
func (*IfFollowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{6}
}

func (x *IfFollowResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CheckLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLikeResponse) Reset() {
	*x = CheckLikeResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLikeResponse) ProtoMessage() {}

func (x *CheckLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLikeResponse.ProtoReflect.Descriptor instead.
func (*CheckLikeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{7}
}

func (x *CheckLikeResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	ParentID      int64                  `protobuf:"varint,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ReplyID       int64                  `protobuf:"varint,3,opt,name=ReplyID,proto3" json:"ReplyID,omitempty"`
	UserID        int64                  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCommentRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *CreateCommentRequest) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *CreateCommentRequest) GetReplyID() int64 {
	if x != nil {
		return x.ReplyID
	}
	return 0
}

func (x *CreateCommentRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentID     int64                  `protobuf:"varint,1,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCommentRequest) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CommentIDUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentID     int64                  `protobuf:"varint,1,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentIDUserIDRequest) Reset() {
	*x = CommentIDUserIDRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentIDUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentIDUserIDRequest) ProtoMessage() {}

func (x *CommentIDUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentIDUserIDRequest.ProtoReflect.Descriptor instead.
func (*CommentIDUserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{10}
}

func (x *CommentIDUserIDRequest) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

func (x *CommentIDUserIDRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CheckCommentDelAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCommentDelAuthResponse) Reset() {
	*x = CheckCommentDelAuthResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCommentDelAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCommentDelAuthResponse) ProtoMessage() {}

func (x *CheckCommentDelAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCommentDelAuthResponse.ProtoReflect.Descriptor instead.
func (*CheckCommentDelAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{11}
}

func (x *CheckCommentDelAuthResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListCommentByPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	PageNo        uint32                 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentByPageRequest) Reset() {
	*x = ListCommentByPageRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentByPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentByPageRequest) ProtoMessage() {}

func (x *ListCommentByPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentByPageRequest.ProtoReflect.Descriptor instead.
func (*ListCommentByPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{12}
}

func (x *ListCommentByPageRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *ListCommentByPageRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListCommentByPageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReplyByPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentID     int64                  `protobuf:"varint,1,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	PageNo        uint32                 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplyByPageRequest) Reset() {
	*x = ListReplyByPageRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplyByPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyByPageRequest) ProtoMessage() {}

func (x *ListReplyByPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyByPageRequest.ProtoReflect.Descriptor instead.
func (*ListReplyByPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{13}
}

func (x *ListReplyByPageRequest) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

func (x *ListReplyByPageRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListReplyByPageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type InteractiveComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PostID        int64                  `protobuf:"varint,2,opt,name=PostID,proto3" json:"PostID,omitempty"`
	ParentID      int64                  `protobuf:"varint,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ReplyID       int64                  `protobuf:"varint,4,opt,name=ReplyID,proto3" json:"ReplyID,omitempty"`
	UserID        int64                  `protobuf:"varint,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveComment) Reset() {
	*x = InteractiveComment{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveComment) ProtoMessage() {}

func (x *InteractiveComment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveComment.ProtoReflect.Descriptor instead.
func (*InteractiveComment) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{14}
}

func (x *InteractiveComment) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *InteractiveComment) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *InteractiveComment) GetParentID() int64 {
	if x != nil {
		return x.ParentID
	}
	return 0
}

func (x *InteractiveComment) GetReplyID() int64 {
	if x != nil {
		return x.ReplyID
	}
	return 0
}

func (x *InteractiveComment) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *InteractiveComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Comments      []*InteractiveComment  `protobuf:"bytes,2,rep,name=Comments,proto3" json:"Comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsResponse) Reset() {
	*x = CommentsResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsResponse) ProtoMessage() {}

func (x *CommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsResponse.ProtoReflect.Descriptor instead.
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{15}
}

func (x *CommentsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CommentsResponse) GetComments() []*InteractiveComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ListFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PageNo        uint32                 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowRequest) Reset() {
	*x = ListFollowRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowRequest) ProtoMessage() {}

func (x *ListFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowRequest.ProtoReflect.Descriptor instead.
func (*ListFollowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{16}
}

func (x *ListFollowRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ListFollowRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListFollowRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	IDs           []int64                `protobuf:"varint,2,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowResponse) Reset() {
	*x = ListFollowResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowResponse) ProtoMessage() {}

func (x *ListFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowResponse.ProtoReflect.Descriptor instead.
func (*ListFollowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{17}
}

func (x *ListFollowResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListFollowResponse) GetIDs() []int64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type InteractiveEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveEmptyResponse) Reset() {
	*x = InteractiveEmptyResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveEmptyResponse) ProtoMessage() {}

func (x *InteractiveEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveEmptyResponse.ProtoReflect.Descriptor instead.
func (*InteractiveEmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{18}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{19}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interactive_v1_interactive_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_interactive_v1_interactive_proto_rawDescGZIP(), []int{20}
}

var File_api_proto_interactive_v1_interactive_proto protoreflect.FileDescriptor

const file_api_proto_interactive_v1_interactive_proto_rawDesc = "" +
	"\n" +
	"*api/proto/interactive/v1/interactive.proto\x12\x0einteractive.v1\"e\n" +
	"\x0fPostInteractive\x12\x18\n" +
	"\aReadCnt\x18\x01 \x01(\x03R\aReadCnt\x12\x18\n" +
	"\aLikeCnt\x18\x02 \x01(\x03R\aLikeCnt\x12\x1e\n" +
	"\n" +
	"CommentCnt\x18\x03 \x01(\x03R\n" +
	"CommentCnt\"/\n" +
	"\x0fUserInteractive\x12\x1c\n" +
	"\tFollowCnt\x18\x01 \x01(\x03R\tFollowCnt\"'\n" +
	"\rPostIDRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\"'\n" +
	"\rUserIDRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\"=\n" +
	"\vLikeRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x16\n" +
	"\x06PostID\x18\x02 \x01(\x03R\x06PostID\"O\n" +
	"\rFollowRequest\x12\x1e\n" +
	"\n" +
	"FollowerID\x18\x01 \x01(\x03R\n" +
	"FollowerID\x12\x1e\n" +
	"\n" +
	"FolloweeID\x18\x02 \x01(\x03R\n" +
	"FolloweeID\"*\n" +
	"\x10IfFollowResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\x05R\x06Result\"+\n" +
	"\x11CheckLikeResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\"\x96\x01\n" +
	"\x14CreateCommentRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x1a\n" +
	"\bParentID\x18\x02 \x01(\x03R\bParentID\x12\x18\n" +
	"\aReplyID\x18\x03 \x01(\x03R\aReplyID\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\x03R\x06UserID\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\"L\n" +
	"\x14DeleteCommentRequest\x12\x1c\n" +
	"\tCommentID\x18\x01 \x01(\x03R\tCommentID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"N\n" +
	"\x16CommentIDUserIDRequest\x12\x1c\n" +
	"\tCommentID\x18\x01 \x01(\x03R\tCommentID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"5\n" +
	"\x1bCheckCommentDelAuthResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\"f\n" +
	"\x18ListCommentByPageRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\rR\bPageSize\"j\n" +
	"\x16ListReplyByPageRequest\x12\x1c\n" +
	"\tCommentID\x18\x01 \x01(\x03R\tCommentID\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\rR\bPageSize\"\xa4\x01\n" +
	"\x12InteractiveComment\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06PostID\x18\x02 \x01(\x03R\x06PostID\x12\x1a\n" +
	"\bParentID\x18\x03 \x01(\x03R\bParentID\x12\x18\n" +
	"\aReplyID\x18\x04 \x01(\x03R\aReplyID\x12\x16\n" +
	"\x06UserID\x18\x05 \x01(\x03R\x06UserID\x12\x18\n" +
	"\aContent\x18\x06 \x01(\tR\aContent\"h\n" +
	"\x10CommentsResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x04R\x05Count\x12>\n" +
	"\bComments\x18\x02 \x03(\v2\".interactive.v1.InteractiveCommentR\bComments\"_\n" +
	"\x11ListFollowRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\rR\bPageSize\"<\n" +
	"\x12ListFollowResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x04R\x05Count\x12\x10\n" +
	"\x03IDs\x18\x02 \x03(\x03R\x03IDs\"\x1a\n" +
	"\x18InteractiveEmptyResponse\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\x87\v\n" +
	"\x12InteractiveService\x12T\n" +
	"\x12GetPostInteractive\x12\x1d.interactive.v1.PostIDRequest\x1a\x1f.interactive.v1.PostInteractive\x12T\n" +
	"\x12GetUserInteractive\x12\x1d.interactive.v1.UserIDRequest\x1a\x1f.interactive.v1.UserInteractive\x12M\n" +
	"\x04Like\x12\x1b.interactive.v1.LikeRequest\x1a(.interactive.v1.InteractiveEmptyResponse\x12O\n" +
	"\x06Unlike\x12\x1b.interactive.v1.LikeRequest\x1a(.interactive.v1.InteractiveEmptyResponse\x12K\n" +
	"\tCheckLike\x12\x1b.interactive.v1.LikeRequest\x1a!.interactive.v1.CheckLikeResponse\x12Q\n" +
	"\x06Follow\x12\x1d.interactive.v1.FollowRequest\x1a(.interactive.v1.InteractiveEmptyResponse\x12S\n" +
	"\bUnfollow\x12\x1d.interactive.v1.FollowRequest\x1a(.interactive.v1.InteractiveEmptyResponse\x12K\n" +
	"\bIfFollow\x12\x1d.interactive.v1.FollowRequest\x1a .interactive.v1.IfFollowResponse\x12S\n" +
	"\aComment\x12$.interactive.v1.CreateCommentRequest\x1a\".interactive.v1.InteractiveComment\x12\\\n" +
	"\n" +
	"DelComment\x12$.interactive.v1.DeleteCommentRequest\x1a(.interactive.v1.InteractiveEmptyResponse\x12_\n" +
	"\x11ListCommentByPage\x12(.interactive.v1.ListCommentByPageRequest\x1a .interactive.v1.CommentsResponse\x12]\n" +
	"\x11ListRepliesByPage\x12&.interactive.v1.ListReplyByPageRequest\x1a .interactive.v1.CommentsResponse\x12j\n" +
	"\x13CheckCommentDelAuth\x12&.interactive.v1.CommentIDUserIDRequest\x1a+.interactive.v1.CheckCommentDelAuthResponse\x12U\n" +
	"\fGetFollowers\x12!.interactive.v1.ListFollowRequest\x1a\".interactive.v1.ListFollowResponse\x12U\n" +
	"\fGetFollowees\x12!.interactive.v1.ListFollowRequest\x1a\".interactive.v1.ListFollowResponse\x12V\n" +
	"\vHealthCheck\x12\".interactive.v1.HealthCheckRequest\x1a#.interactive.v1.HealthCheckResponseBJZHgithub.com/yzletter/go-postery/api/proto/interactive/v1;interactive_grpcb\x06proto3"

var (
	file_api_proto_interactive_v1_interactive_proto_rawDescOnce sync.Once
	file_api_proto_interactive_v1_interactive_proto_rawDescData []byte
)

func file_api_proto_interactive_v1_interactive_proto_rawDescGZIP() []byte {
	file_api_proto_interactive_v1_interactive_proto_rawDescOnce.Do(func() {
		file_api_proto_interactive_v1_interactive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_interactive_v1_interactive_proto_rawDesc), len(file_api_proto_interactive_v1_interactive_proto_rawDesc)))
	})
	return file_api_proto_interactive_v1_interactive_proto_rawDescData
}

var file_api_proto_interactive_v1_interactive_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_interactive_v1_interactive_proto_goTypes = []any{
	(*PostInteractive)(nil),             // 0: interactive.v1.PostInteractive
	(*UserInteractive)(nil),             // 1: interactive.v1.UserInteractive
	(*PostIDRequest)(nil),               // 2: interactive.v1.PostIDRequest
	(*UserIDRequest)(nil),               // 3: interactive.v1.UserIDRequest
	(*LikeRequest)(nil),                 // 4: interactive.v1.LikeRequest
	(*FollowRequest)(nil),               // 5: interactive.v1.FollowRequest
	(*IfFollowResponse)(nil),            // 6: interactive.v1.IfFollowResponse
	(*CheckLikeResponse)(nil),           // 7: interactive.v1.CheckLikeResponse
	(*CreateCommentRequest)(nil),        // 8: interactive.v1.CreateCommentRequest
	(*DeleteCommentRequest)(nil),        // 9: interactive.v1.DeleteCommentRequest
	(*CommentIDUserIDRequest)(nil),      // 10: interactive.v1.CommentIDUserIDRequest
	(*CheckCommentDelAuthResponse)(nil), // 11: interactive.v1.CheckCommentDelAuthResponse
	(*ListCommentByPageRequest)(nil),    // 12: interactive.v1.ListCommentByPageRequest
	(*ListReplyByPageRequest)(nil),      // 13: interactive.v1.ListReplyByPageRequest
	(*InteractiveComment)(nil),          // 14: interactive.v1.InteractiveComment
	(*CommentsResponse)(nil),            // 15: interactive.v1.CommentsResponse
	(*ListFollowRequest)(nil),           // 16: interactive.v1.ListFollowRequest
	(*ListFollowResponse)(nil),          // 17: interactive.v1.ListFollowResponse
	(*InteractiveEmptyResponse)(nil),    // 18: interactive.v1.InteractiveEmptyResponse
	(*HealthCheckRequest)(nil),          // 19: interactive.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 20: interactive.v1.HealthCheckResponse
}
var file_api_proto_interactive_v1_interactive_proto_depIdxs = []int32{
	14, // 0: interactive.v1.CommentsResponse.Comments:type_name -> interactive.v1.InteractiveComment
	2,  // 1: interactive.v1.InteractiveService.GetPostInteractive:input_type -> interactive.v1.PostIDRequest
	3,  // 2: interactive.v1.InteractiveService.GetUserInteractive:input_type -> interactive.v1.UserIDRequest
	4,  // 3: interactive.v1.InteractiveService.Like:input_type -> interactive.v1.LikeRequest
	4,  // 4: interactive.v1.InteractiveService.Unlike:input_type -> interactive.v1.LikeRequest
	4,  // 5: interactive.v1.InteractiveService.CheckLike:input_type -> interactive.v1.LikeRequest
	5,  // 6: interactive.v1.InteractiveService.Follow:input_type -> interactive.v1.FollowRequest
	5,  // 7: interactive.v1.InteractiveService.Unfollow:input_type -> interactive.v1.FollowRequest
	5,  // 8: interactive.v1.InteractiveService.IfFollow:input_type -> interactive.v1.FollowRequest
	8,  // 9: interactive.v1.InteractiveService.Comment:input_type -> interactive.v1.CreateCommentRequest
	9,  // 10: interactive.v1.InteractiveService.DelComment:input_type -> interactive.v1.DeleteCommentRequest
	12, // 11: interactive.v1.InteractiveService.ListCommentByPage:input_type -> interactive.v1.ListCommentByPageRequest
	13, // 12: interactive.v1.InteractiveService.ListRepliesByPage:input_type -> interactive.v1.ListReplyByPageRequest
	10, // 13: interactive.v1.InteractiveService.CheckCommentDelAuth:input_type -> interactive.v1.CommentIDUserIDRequest
	16, // 14: interactive.v1.InteractiveService.GetFollowers:input_type -> interactive.v1.ListFollowRequest
	16, // 15: interactive.v1.InteractiveService.GetFollowees:input_type -> interactive.v1.ListFollowRequest
	19, // 16: interactive.v1.InteractiveService.HealthCheck:input_type -> interactive.v1.HealthCheckRequest
	0,  // 17: interactive.v1.InteractiveService.GetPostInteractive:output_type -> interactive.v1.PostInteractive
	1,  // 18: interactive.v1.InteractiveService.GetUserInteractive:output_type -> interactive.v1.UserInteractive
	18, // 19: interactive.v1.InteractiveService.Like:output_type -> interactive.v1.InteractiveEmptyResponse
	18, // 20: interactive.v1.InteractiveService.Unlike:output_type -> interactive.v1.InteractiveEmptyResponse
	7,  // 21: interactive.v1.InteractiveService.CheckLike:output_type -> interactive.v1.CheckLikeResponse
	18, // 22: interactive.v1.InteractiveService.Follow:output_type -> interactive.v1.InteractiveEmptyResponse
	18, // 23: interactive.v1.InteractiveService.Unfollow:output_type -> interactive.v1.InteractiveEmptyResponse
	6,  // 24: interactive.v1.InteractiveService.IfFollow:output_type -> interactive.v1.IfFollowResponse
	14, // 25: interactive.v1.InteractiveService.Comment:output_type -> interactive.v1.InteractiveComment
	18, // 26: interactive.v1.InteractiveService.DelComment:output_type -> interactive.v1.InteractiveEmptyResponse
	15, // 27: interactive.v1.InteractiveService.ListCommentByPage:output_type -> interactive.v1.CommentsResponse
	15, // 28: interactive.v1.InteractiveService.ListRepliesByPage:output_type -> interactive.v1.CommentsResponse
	11, // 29: interactive.v1.InteractiveService.CheckCommentDelAuth:output_type -> interactive.v1.CheckCommentDelAuthResponse
	17, // 30: interactive.v1.InteractiveService.GetFollowers:output_type -> interactive.v1.ListFollowResponse
	17, // 31: interactive.v1.InteractiveService.GetFollowees:output_type -> interactive.v1.ListFollowResponse
	20, // 32: interactive.v1.InteractiveService.HealthCheck:output_type -> interactive.v1.HealthCheckResponse
	17, // [17:33] is the sub-list for method output_type
	1,  // [1:17] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_interactive_v1_interactive_proto_init() }
func file_api_proto_interactive_v1_interactive_proto_init() {
	if File_api_proto_interactive_v1_interactive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_interactive_v1_interactive_proto_rawDesc), len(file_api_proto_interactive_v1_interactive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_interactive_v1_interactive_proto_goTypes,
		DependencyIndexes: file_api_proto_interactive_v1_interactive_proto_depIdxs,
		MessageInfos:      file_api_proto_interactive_v1_interactive_proto_msgTypes,
	}.Build()
	File_api_proto_interactive_v1_interactive_proto = out.File
	file_api_proto_interactive_v1_interactive_proto_goTypes = nil
	file_api_proto_interactive_v1_interactive_proto_depIdxs = nil
}
