# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this conf.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
        # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this conf.
        labels:
          app: "prometheus"
  - job_name: "code_service"
    static_configs:
      - targets: ["172.16.150.246:9101","172.16.57.13:9101","172.16.52.125:9101"]
    metrics_path: "/metrics"
  - job_name: "lottery_service"
    static_configs:
      - targets: [ "172.16.150.246:9103","172.16.52.125:9103"]
    metrics_path: "/metrics"