// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/user/v1/user.proto

package user_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserBrief) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UserBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type TopUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *TopUser) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TopUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TopUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *TopUser) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *TopUser) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetProfileByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIdRequest) Reset() {
	*x = GetProfileByIdRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIdRequest) ProtoMessage() {}

func (x *GetProfileByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileByIdRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetProfileByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Gender        uint32                 `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	LastLoginIP   string                 `protobuf:"bytes,9,opt,name=LastLoginIP,proto3" json:"LastLoginIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIdResponse) Reset() {
	*x = GetProfileByIdResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIdResponse) ProtoMessage() {}

func (x *GetProfileByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileByIdResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetProfileByIdResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetProfileByIdResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetProfileByIdResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetProfileByIdResponse) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetProfileByIdResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *GetProfileByIdResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetProfileByIdResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetProfileByIdResponse) GetLastLoginIP() string {
	if x != nil {
		return x.LastLoginIP
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=Bio,proto3" json:"Bio,omitempty"`
	Gender        uint32                 `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=Country,proto3" json:"Country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateProfileRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateProfileRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{5}
}

type TopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{6}
}

type TopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUsers      []*TopUser             `protobuf:"bytes,1,rep,name=TopUsers,proto3" json:"TopUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopResponse) Reset() {
	*x = TopResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopResponse) ProtoMessage() {}

func (x *TopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopResponse.ProtoReflect.Descriptor instead.
func (*TopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *TopResponse) GetTopUsers() []*TopUser {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

var File_api_proto_user_v1_user_proto protoreflect.FileDescriptor

const file_api_proto_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/user/v1/user.proto\x12\auser.v1\"O\n" +
	"\tUserBrief\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\"u\n" +
	"\aTopUser\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x10\n" +
	"\x03Bio\x18\x04 \x01(\tR\x03Bio\x12\x14\n" +
	"\x05Score\x18\x05 \x01(\x02R\x05Score\"'\n" +
	"\x15GetProfileByIdRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"\xfa\x01\n" +
	"\x16GetProfileByIdResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x10\n" +
	"\x03Bio\x18\x04 \x01(\tR\x03Bio\x12\x16\n" +
	"\x06Gender\x18\x05 \x01(\rR\x06Gender\x12\x1a\n" +
	"\bBirthday\x18\x06 \x01(\tR\bBirthday\x12\x1a\n" +
	"\bLocation\x18\a \x01(\tR\bLocation\x12\x18\n" +
	"\aCountry\x18\b \x01(\tR\aCountry\x12 \n" +
	"\vLastLoginIP\x18\t \x01(\tR\vLastLoginIP\"\xd6\x01\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x10\n" +
	"\x03Bio\x18\x04 \x01(\tR\x03Bio\x12\x16\n" +
	"\x06Gender\x18\x05 \x01(\rR\x06Gender\x12\x1a\n" +
	"\bBirthday\x18\x06 \x01(\tR\bBirthday\x12\x1a\n" +
	"\bLocation\x18\a \x01(\tR\bLocation\x12\x18\n" +
	"\aCountry\x18\b \x01(\tR\aCountry\"\x17\n" +
	"\x15UpdateProfileResponse\"\f\n" +
	"\n" +
	"TopRequest\";\n" +
	"\vTopResponse\x12,\n" +
	"\bTopUsers\x18\x01 \x03(\v2\x10.user.v1.TopUserR\bTopUsers2\xe2\x01\n" +
	"\vUserService\x12Q\n" +
	"\x0eGetProfileById\x12\x1e.user.v1.GetProfileByIdRequest\x1a\x1f.user.v1.GetProfileByIdResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateProfileRequest\x1a\x1e.user.v1.UpdateProfileResponse\x120\n" +
	"\x03Top\x12\x13.user.v1.TopRequest\x1a\x14.user.v1.TopResponseB<Z:github.com/yzletter/go-postery/api/proto/user/v1;user_grpcb\x06proto3"

var (
	file_api_proto_user_v1_user_proto_rawDescOnce sync.Once
	file_api_proto_user_v1_user_proto_rawDescData []byte
)

func file_api_proto_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_v1_user_proto_rawDesc), len(file_api_proto_user_v1_user_proto_rawDesc)))
	})
	return file_api_proto_user_v1_user_proto_rawDescData
}

var file_api_proto_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_user_v1_user_proto_goTypes = []any{
	(*UserBrief)(nil),              // 0: user.v1.UserBrief
	(*TopUser)(nil),                // 1: user.v1.TopUser
	(*GetProfileByIdRequest)(nil),  // 2: user.v1.GetProfileByIdRequest
	(*GetProfileByIdResponse)(nil), // 3: user.v1.GetProfileByIdResponse
	(*UpdateProfileRequest)(nil),   // 4: user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 5: user.v1.UpdateProfileResponse
	(*TopRequest)(nil),             // 6: user.v1.TopRequest
	(*TopResponse)(nil),            // 7: user.v1.TopResponse
}
var file_api_proto_user_v1_user_proto_depIdxs = []int32{
	1, // 0: user.v1.TopResponse.TopUsers:type_name -> user.v1.TopUser
	2, // 1: user.v1.UserService.GetProfileById:input_type -> user.v1.GetProfileByIdRequest
	4, // 2: user.v1.UserService.UpdateProfile:input_type -> user.v1.UpdateProfileRequest
	6, // 3: user.v1.UserService.Top:input_type -> user.v1.TopRequest
	3, // 4: user.v1.UserService.GetProfileById:output_type -> user.v1.GetProfileByIdResponse
	5, // 5: user.v1.UserService.UpdateProfile:output_type -> user.v1.UpdateProfileResponse
	7, // 6: user.v1.UserService.Top:output_type -> user.v1.TopResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_user_v1_user_proto_init() }
func file_api_proto_user_v1_user_proto_init() {
	if File_api_proto_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_v1_user_proto_rawDesc), len(file_api_proto_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_v1_user_proto_depIdxs,
		MessageInfos:      file_api_proto_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_v1_user_proto = out.File
	file_api_proto_user_v1_user_proto_goTypes = nil
	file_api_proto_user_v1_user_proto_depIdxs = nil
}
