// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/session/v1/session.proto

package session_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionService_ListByUID_FullMethodName                = "/session.v1.SessionService/ListByUID"
	SessionService_GetSession_FullMethodName               = "/session.v1.SessionService/GetSession"
	SessionService_GetHistoryMessagesByPage_FullMethodName = "/session.v1.SessionService/GetHistoryMessagesByPage"
	SessionService_Delete_FullMethodName                   = "/session.v1.SessionService/Delete"
	SessionService_UpdateUnread_FullMethodName             = "/session.v1.SessionService/UpdateUnread"
	SessionService_ClearUnread_FullMethodName              = "/session.v1.SessionService/ClearUnread"
	SessionService_CreateMessage_FullMethodName            = "/session.v1.SessionService/CreateMessage"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	ListByUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Sessions, error)
	GetSession(ctx context.Context, in *BothUserID, opts ...grpc.CallOption) (*Session, error)
	GetHistoryMessagesByPage(ctx context.Context, in *GetHistoryMessagesByPageRequest, opts ...grpc.CallOption) (*GetHistoryMessagesByPageResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error)
	UpdateUnread(ctx context.Context, in *UpdateUnreadRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error)
	ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error)
	CreateMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*SessionEmptyResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) ListByUID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Sessions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sessions)
	err := c.cc.Invoke(ctx, SessionService_ListByUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSession(ctx context.Context, in *BothUserID, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetHistoryMessagesByPage(ctx context.Context, in *GetHistoryMessagesByPageRequest, opts ...grpc.CallOption) (*GetHistoryMessagesByPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryMessagesByPageResponse)
	err := c.cc.Invoke(ctx, SessionService_GetHistoryMessagesByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEmptyResponse)
	err := c.cc.Invoke(ctx, SessionService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) UpdateUnread(ctx context.Context, in *UpdateUnreadRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEmptyResponse)
	err := c.cc.Invoke(ctx, SessionService_UpdateUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*SessionEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEmptyResponse)
	err := c.cc.Invoke(ctx, SessionService_ClearUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CreateMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*SessionEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionEmptyResponse)
	err := c.cc.Invoke(ctx, SessionService_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
type SessionServiceServer interface {
	ListByUID(context.Context, *UserID) (*Sessions, error)
	GetSession(context.Context, *BothUserID) (*Session, error)
	GetHistoryMessagesByPage(context.Context, *GetHistoryMessagesByPageRequest) (*GetHistoryMessagesByPageResponse, error)
	Delete(context.Context, *DeleteRequest) (*SessionEmptyResponse, error)
	UpdateUnread(context.Context, *UpdateUnreadRequest) (*SessionEmptyResponse, error)
	ClearUnread(context.Context, *ClearUnreadRequest) (*SessionEmptyResponse, error)
	CreateMessage(context.Context, *Message) (*SessionEmptyResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) ListByUID(context.Context, *UserID) (*Sessions, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByUID not implemented")
}
func (UnimplementedSessionServiceServer) GetSession(context.Context, *BothUserID) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionServiceServer) GetHistoryMessagesByPage(context.Context, *GetHistoryMessagesByPageRequest) (*GetHistoryMessagesByPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryMessagesByPage not implemented")
}
func (UnimplementedSessionServiceServer) Delete(context.Context, *DeleteRequest) (*SessionEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSessionServiceServer) UpdateUnread(context.Context, *UpdateUnreadRequest) (*SessionEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUnread not implemented")
}
func (UnimplementedSessionServiceServer) ClearUnread(context.Context, *ClearUnreadRequest) (*SessionEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearUnread not implemented")
}
func (UnimplementedSessionServiceServer) CreateMessage(context.Context, *Message) (*SessionEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_ListByUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListByUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListByUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListByUID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BothUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSession(ctx, req.(*BothUserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetHistoryMessagesByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryMessagesByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetHistoryMessagesByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetHistoryMessagesByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetHistoryMessagesByPage(ctx, req.(*GetHistoryMessagesByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_UpdateUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).UpdateUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_UpdateUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).UpdateUnread(ctx, req.(*UpdateUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ClearUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ClearUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ClearUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ClearUnread(ctx, req.(*ClearUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.v1.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByUID",
			Handler:    _SessionService_ListByUID_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionService_GetSession_Handler,
		},
		{
			MethodName: "GetHistoryMessagesByPage",
			Handler:    _SessionService_GetHistoryMessagesByPage_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SessionService_Delete_Handler,
		},
		{
			MethodName: "UpdateUnread",
			Handler:    _SessionService_UpdateUnread_Handler,
		},
		{
			MethodName: "ClearUnread",
			Handler:    _SessionService_ClearUnread_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _SessionService_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/session/v1/session.proto",
}
