syntax = "proto3";

package index_service;

option go_package = "github.com/yzletter/go-postery/search/service/index_service;index_service";

import "search/model/document.proto";
import "search/model/term_query.proto";

message DocID {
  string DocID = 1;
}

message AffectedCount {
  int32 Count = 1;
}

message SearchRequest{
  model.TermQuery TermQuery = 1;
  uint64 OnFlag = 2;
  uint64 OffFlag = 3;
  repeated uint64 OrFlags = 4;
}

message SearchResult {
  repeated model.Document Results = 1;
}

message CountRequest{
}

message HealthCheckRequest {}
message HealthCheckResponse {}

// 定义服务
service IndexService {
  rpc AddDoc(model.Document) returns (AffectedCount);
  rpc DeleteDoc(DocID) returns (AffectedCount);
  rpc Search(SearchRequest) returns (SearchResult);
  rpc Count(CountRequest) returns (AffectedCount);
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
}

/*
protoc \
-I . \
search/service/index_service/index.proto \
--go_out=. \
--go-grpc_out=. \
--go_opt=paths=source_relative \
--go-grpc_opt=paths=source_relative
 */
