// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: search/service/index_service/index.proto

package index_service

import (
	model "github.com/yzletter/go-postery/microservice-backend/search/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocID         string                 `protobuf:"bytes,1,opt,name=DocID,proto3" json:"DocID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocID) Reset() {
	*x = DocID{}
	mi := &file_search_service_index_service_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocID) ProtoMessage() {}

func (x *DocID) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocID.ProtoReflect.Descriptor instead.
func (*DocID) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{0}
}

func (x *DocID) GetDocID() string {
	if x != nil {
		return x.DocID
	}
	return ""
}

type AffectedCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedCount) Reset() {
	*x = AffectedCount{}
	mi := &file_search_service_index_service_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedCount) ProtoMessage() {}

func (x *AffectedCount) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedCount.ProtoReflect.Descriptor instead.
func (*AffectedCount) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{1}
}

func (x *AffectedCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermQuery     *model.TermQuery       `protobuf:"bytes,1,opt,name=TermQuery,proto3" json:"TermQuery,omitempty"`
	OnFlag        uint64                 `protobuf:"varint,2,opt,name=OnFlag,proto3" json:"OnFlag,omitempty"`
	OffFlag       uint64                 `protobuf:"varint,3,opt,name=OffFlag,proto3" json:"OffFlag,omitempty"`
	OrFlags       []uint64               `protobuf:"varint,4,rep,packed,name=OrFlags,proto3" json:"OrFlags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_service_index_service_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetTermQuery() *model.TermQuery {
	if x != nil {
		return x.TermQuery
	}
	return nil
}

func (x *SearchRequest) GetOnFlag() uint64 {
	if x != nil {
		return x.OnFlag
	}
	return 0
}

func (x *SearchRequest) GetOffFlag() uint64 {
	if x != nil {
		return x.OffFlag
	}
	return 0
}

func (x *SearchRequest) GetOrFlags() []uint64 {
	if x != nil {
		return x.OrFlags
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*model.Document      `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_search_service_index_service_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetResults() []*model.Document {
	if x != nil {
		return x.Results
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_search_service_index_service_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{4}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_search_service_index_service_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_search_service_index_service_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_index_service_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_search_service_index_service_index_proto_rawDescGZIP(), []int{6}
}

var File_search_service_index_service_index_proto protoreflect.FileDescriptor

const file_search_service_index_service_index_proto_rawDesc = "" +
	"\n" +
	"(search/service/index_service/index.proto\x12\rindex_service\x1a\x1bsearch/model/document.proto\x1a\x1dsearch/model/term_query.proto\"\x1d\n" +
	"\x05DocID\x12\x14\n" +
	"\x05DocID\x18\x01 \x01(\tR\x05DocID\"%\n" +
	"\rAffectedCount\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\"\x8b\x01\n" +
	"\rSearchRequest\x12.\n" +
	"\tTermQuery\x18\x01 \x01(\v2\x10.model.TermQueryR\tTermQuery\x12\x16\n" +
	"\x06OnFlag\x18\x02 \x01(\x04R\x06OnFlag\x12\x18\n" +
	"\aOffFlag\x18\x03 \x01(\x04R\aOffFlag\x12\x18\n" +
	"\aOrFlags\x18\x04 \x03(\x04R\aOrFlags\"9\n" +
	"\fSearchResult\x12)\n" +
	"\aResults\x18\x01 \x03(\v2\x0f.model.DocumentR\aResults\"\x0e\n" +
	"\fCountRequest\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xe7\x02\n" +
	"\fIndexService\x127\n" +
	"\x06AddDoc\x12\x0f.model.Document\x1a\x1c.index_service.AffectedCount\x12?\n" +
	"\tDeleteDoc\x12\x14.index_service.DocID\x1a\x1c.index_service.AffectedCount\x12C\n" +
	"\x06Search\x12\x1c.index_service.SearchRequest\x1a\x1b.index_service.SearchResult\x12B\n" +
	"\x05Count\x12\x1b.index_service.CountRequest\x1a\x1c.index_service.AffectedCount\x12T\n" +
	"\vHealthCheck\x12!.index_service.HealthCheckRequest\x1a\".index_service.HealthCheckResponseBKZIgithub.com/yzletter/go-postery/search/service/index_service;index_serviceb\x06proto3"

var (
	file_search_service_index_service_index_proto_rawDescOnce sync.Once
	file_search_service_index_service_index_proto_rawDescData []byte
)

func file_search_service_index_service_index_proto_rawDescGZIP() []byte {
	file_search_service_index_service_index_proto_rawDescOnce.Do(func() {
		file_search_service_index_service_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_service_index_service_index_proto_rawDesc), len(file_search_service_index_service_index_proto_rawDesc)))
	})
	return file_search_service_index_service_index_proto_rawDescData
}

var file_search_service_index_service_index_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_search_service_index_service_index_proto_goTypes = []any{
	(*DocID)(nil),               // 0: index_service.DocID
	(*AffectedCount)(nil),       // 1: index_service.AffectedCount
	(*SearchRequest)(nil),       // 2: index_service.SearchRequest
	(*SearchResult)(nil),        // 3: index_service.SearchResult
	(*CountRequest)(nil),        // 4: index_service.CountRequest
	(*HealthCheckRequest)(nil),  // 5: index_service.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 6: index_service.HealthCheckResponse
	(*model.TermQuery)(nil),     // 7: model.TermQuery
	(*model.Document)(nil),      // 8: model.Document
}
var file_search_service_index_service_index_proto_depIdxs = []int32{
	7, // 0: index_service.SearchRequest.TermQuery:type_name -> model.TermQuery
	8, // 1: index_service.SearchResult.Results:type_name -> model.Document
	8, // 2: index_service.IndexService.AddDoc:input_type -> model.Document
	0, // 3: index_service.IndexService.DeleteDoc:input_type -> index_service.DocID
	2, // 4: index_service.IndexService.Search:input_type -> index_service.SearchRequest
	4, // 5: index_service.IndexService.Count:input_type -> index_service.CountRequest
	5, // 6: index_service.IndexService.HealthCheck:input_type -> index_service.HealthCheckRequest
	1, // 7: index_service.IndexService.AddDoc:output_type -> index_service.AffectedCount
	1, // 8: index_service.IndexService.DeleteDoc:output_type -> index_service.AffectedCount
	3, // 9: index_service.IndexService.Search:output_type -> index_service.SearchResult
	1, // 10: index_service.IndexService.Count:output_type -> index_service.AffectedCount
	6, // 11: index_service.IndexService.HealthCheck:output_type -> index_service.HealthCheckResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_service_index_service_index_proto_init() }
func file_search_service_index_service_index_proto_init() {
	if File_search_service_index_service_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_service_index_service_index_proto_rawDesc), len(file_search_service_index_service_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_service_index_service_index_proto_goTypes,
		DependencyIndexes: file_search_service_index_service_index_proto_depIdxs,
		MessageInfos:      file_search_service_index_service_index_proto_msgTypes,
	}.Build()
	File_search_service_index_service_index_proto = out.File
	file_search_service_index_service_index_proto_goTypes = nil
	file_search_service_index_service_index_proto_depIdxs = nil
}
