// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/search/v1/search.proto

package search_grpc

import (
	model "github.com/yzletter/go-postery/microservice-backend/search/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocID         string                 `protobuf:"bytes,1,opt,name=DocID,proto3" json:"DocID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocID) Reset() {
	*x = DocID{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocID) ProtoMessage() {}

func (x *DocID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocID.ProtoReflect.Descriptor instead.
func (*DocID) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *DocID) GetDocID() string {
	if x != nil {
		return x.DocID
	}
	return ""
}

type AffectedCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedCount) Reset() {
	*x = AffectedCount{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedCount) ProtoMessage() {}

func (x *AffectedCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedCount.ProtoReflect.Descriptor instead.
func (*AffectedCount) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *AffectedCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{2}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=Queries,proto3" json:"Queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermQuery     *model.TermQuery       `protobuf:"bytes,1,opt,name=TermQuery,proto3" json:"TermQuery,omitempty"`
	OnFlag        uint64                 `protobuf:"varint,2,opt,name=OnFlag,proto3" json:"OnFlag,omitempty"`
	OffFlag       uint64                 `protobuf:"varint,3,opt,name=OffFlag,proto3" json:"OffFlag,omitempty"`
	OrFlags       []uint64               `protobuf:"varint,4,rep,packed,name=OrFlags,proto3" json:"OrFlags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetTermQuery() *model.TermQuery {
	if x != nil {
		return x.TermQuery
	}
	return nil
}

func (x *Query) GetOnFlag() uint64 {
	if x != nil {
		return x.OnFlag
	}
	return 0
}

func (x *Query) GetOffFlag() uint64 {
	if x != nil {
		return x.OffFlag
	}
	return 0
}

func (x *Query) GetOrFlags() []uint64 {
	if x != nil {
		return x.OrFlags
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentIDs   []*DocID               `protobuf:"bytes,1,rep,name=DocumentIDs,proto3" json:"DocumentIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResult) GetDocumentIDs() []*DocID {
	if x != nil {
		return x.DocumentIDs
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_search_v1_search_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_search_proto_rawDesc = "" +
	"\n" +
	" api/proto/search/v1/search.proto\x12\tsearch.v1\x1a\x1bsearch/model/document.proto\x1a\x1dsearch/model/term_query.proto\"\x1d\n" +
	"\x05DocID\x12\x14\n" +
	"\x05DocID\x18\x01 \x01(\tR\x05DocID\"%\n" +
	"\rAffectedCount\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\"\x0e\n" +
	"\fCountRequest\")\n" +
	"\rSearchRequest\x12\x18\n" +
	"\aQueries\x18\x01 \x03(\tR\aQueries\"\x83\x01\n" +
	"\x05Query\x12.\n" +
	"\tTermQuery\x18\x01 \x01(\v2\x10.model.TermQueryR\tTermQuery\x12\x16\n" +
	"\x06OnFlag\x18\x02 \x01(\x04R\x06OnFlag\x12\x18\n" +
	"\aOffFlag\x18\x03 \x01(\x04R\aOffFlag\x12\x18\n" +
	"\aOrFlags\x18\x04 \x03(\x04R\aOrFlags\"B\n" +
	"\fSearchResult\x122\n" +
	"\vDocumentIDs\x18\x01 \x03(\v2\x10.search.v1.DocIDR\vDocumentIDs\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xc4\x02\n" +
	"\rSearchService\x12;\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x17.search.v1.SearchResult\x127\n" +
	"\tDeleteDoc\x12\x10.search.v1.DocID\x1a\x18.search.v1.AffectedCount\x123\n" +
	"\x06AddDoc\x12\x0f.model.Document\x1a\x18.search.v1.AffectedCount\x12:\n" +
	"\x05Count\x12\x17.search.v1.CountRequest\x1a\x18.search.v1.AffectedCount\x12L\n" +
	"\vHealthCheck\x12\x1d.search.v1.HealthCheckRequest\x1a\x1e.search.v1.HealthCheckResponseB@Z>github.com/yzletter/go-postery/api/proto/search/v1;search_grpcb\x06proto3"

var (
	file_api_proto_search_v1_search_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_search_proto_rawDescData []byte
)

func file_api_proto_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)))
	})
	return file_api_proto_search_v1_search_proto_rawDescData
}

var file_api_proto_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_search_v1_search_proto_goTypes = []any{
	(*DocID)(nil),               // 0: search.v1.DocID
	(*AffectedCount)(nil),       // 1: search.v1.AffectedCount
	(*CountRequest)(nil),        // 2: search.v1.CountRequest
	(*SearchRequest)(nil),       // 3: search.v1.SearchRequest
	(*Query)(nil),               // 4: search.v1.Query
	(*SearchResult)(nil),        // 5: search.v1.SearchResult
	(*HealthCheckRequest)(nil),  // 6: search.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: search.v1.HealthCheckResponse
	(*model.TermQuery)(nil),     // 8: model.TermQuery
	(*model.Document)(nil),      // 9: model.Document
}
var file_api_proto_search_v1_search_proto_depIdxs = []int32{
	8, // 0: search.v1.Query.TermQuery:type_name -> model.TermQuery
	0, // 1: search.v1.SearchResult.DocumentIDs:type_name -> search.v1.DocID
	3, // 2: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	0, // 3: search.v1.SearchService.DeleteDoc:input_type -> search.v1.DocID
	9, // 4: search.v1.SearchService.AddDoc:input_type -> model.Document
	2, // 5: search.v1.SearchService.Count:input_type -> search.v1.CountRequest
	6, // 6: search.v1.SearchService.HealthCheck:input_type -> search.v1.HealthCheckRequest
	5, // 7: search.v1.SearchService.Search:output_type -> search.v1.SearchResult
	1, // 8: search.v1.SearchService.DeleteDoc:output_type -> search.v1.AffectedCount
	1, // 9: search.v1.SearchService.AddDoc:output_type -> search.v1.AffectedCount
	1, // 10: search.v1.SearchService.Count:output_type -> search.v1.AffectedCount
	7, // 11: search.v1.SearchService.HealthCheck:output_type -> search.v1.HealthCheckResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_search_proto_init() }
func file_api_proto_search_v1_search_proto_init() {
	if File_api_proto_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_search_proto = out.File
	file_api_proto_search_v1_search_proto_goTypes = nil
	file_api_proto_search_v1_search_proto_depIdxs = nil
}
