syntax = "proto3";

package agent.v1;

option go_package = "github.com/yzletter/go-postery/api/proto/agent/v1;agent_grpc";

message ChatResponse {
  int64 SessionID = 1;
  string Content = 2;
  repeated string Documents = 3; // 参考文献
}

message ChatRequest {
  int64 UserID = 1;
  int64 SessionID = 2;
  string Query = 3;
}

service AgentService {
  rpc Chat(ChatRequest) returns (ChatResponse);
}

/*
protoc \
-I . \
api/proto/agent/v1/agent.proto \
--go_out=. \
--go-grpc_out=. \
--go_opt=paths=source_relative \
--go-grpc_opt=paths=source_relative
*/