// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/post/v1/post.proto

package post_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostService_Create_FullMethodName                 = "/post.v1.PostService/Create"
	PostService_GetDetailByID_FullMethodName          = "/post.v1.PostService/GetDetailByID"
	PostService_GetBriefByID_FullMethodName           = "/post.v1.PostService/GetBriefByID"
	PostService_Top_FullMethodName                    = "/post.v1.PostService/Top"
	PostService_Update_FullMethodName                 = "/post.v1.PostService/Update"
	PostService_ListByPage_FullMethodName             = "/post.v1.PostService/ListByPage"
	PostService_ListByPageAndUid_FullMethodName       = "/post.v1.PostService/ListByPageAndUid"
	PostService_ListByPageAndTag_FullMethodName       = "/post.v1.PostService/ListByPageAndTag"
	PostService_Belong_FullMethodName                 = "/post.v1.PostService/Belong"
	PostService_Delete_FullMethodName                 = "/post.v1.PostService/Delete"
	PostService_Like_FullMethodName                   = "/post.v1.PostService/Like"
	PostService_Unlike_FullMethodName                 = "/post.v1.PostService/Unlike"
	PostService_IfLike_FullMethodName                 = "/post.v1.PostService/IfLike"
	PostService_CreateComment_FullMethodName          = "/post.v1.PostService/CreateComment"
	PostService_DeleteComment_FullMethodName          = "/post.v1.PostService/DeleteComment"
	PostService_ListCommentByPage_FullMethodName      = "/post.v1.PostService/ListCommentByPage"
	PostService_ListRepliesByPage_FullMethodName      = "/post.v1.PostService/ListRepliesByPage"
	PostService_CheckCommentDeleteAuth_FullMethodName = "/post.v1.PostService/CheckCommentDeleteAuth"
	PostService_HealthCheck_FullMethodName            = "/post.v1.PostService/HealthCheck"
)

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostServiceClient interface {
	// 创建帖子
	Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostDetail, error)
	// 根据帖子 ID 查询帖子详情
	GetDetailByID(ctx context.Context, in *GetDetailByIDRequest, opts ...grpc.CallOption) (*PostDetail, error)
	// 根据帖子 ID 查询帖子摘要
	GetBriefByID(ctx context.Context, in *GetBriefByIDRequest, opts ...grpc.CallOption) (*PostBrief, error)
	// 返回推荐帖子
	Top(ctx context.Context, in *PostEmptyRequest, opts ...grpc.CallOption) (*TopResponse, error)
	// 更新帖子
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error)
	// 按页查询帖子
	ListByPage(ctx context.Context, in *ListByPageRequest, opts ...grpc.CallOption) (*PostDetailsResponse, error)
	// 按页 + 用户 ID 查询用户发表的帖子
	ListByPageAndUid(ctx context.Context, in *ListByPageAndUidRequest, opts ...grpc.CallOption) (*PostBriefsResponse, error)
	// 按页 + Tag 查询该 Tag 的帖子
	ListByPageAndTag(ctx context.Context, in *ListByPageAndTagRequest, opts ...grpc.CallOption) (*PostDetailsResponse, error)
	// 查询帖子是否属于用户
	Belong(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*BelongResponse, error)
	// 删除帖子
	Delete(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error)
	// 点赞帖子
	Like(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error)
	// 取消点赞帖子
	Unlike(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error)
	// 查询用户是否点过赞
	IfLike(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*IfLikeResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error)
	// 根据 PostID 按页获取文章主评论
	ListCommentByPage(ctx context.Context, in *ListCommentByPageRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	// 根据 CommentID 按页获取评论的回复
	ListRepliesByPage(ctx context.Context, in *ListReplyByPageRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	// 评论是否属于用户
	CheckCommentDeleteAuth(ctx context.Context, in *CommentBelongRequest, opts ...grpc.CallOption) (*BelongResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDetail)
	err := c.cc.Invoke(ctx, PostService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetDetailByID(ctx context.Context, in *GetDetailByIDRequest, opts ...grpc.CallOption) (*PostDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDetail)
	err := c.cc.Invoke(ctx, PostService_GetDetailByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetBriefByID(ctx context.Context, in *GetBriefByIDRequest, opts ...grpc.CallOption) (*PostBrief, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostBrief)
	err := c.cc.Invoke(ctx, PostService_GetBriefByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Top(ctx context.Context, in *PostEmptyRequest, opts ...grpc.CallOption) (*TopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopResponse)
	err := c.cc.Invoke(ctx, PostService_Top_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostEmptyResponse)
	err := c.cc.Invoke(ctx, PostService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListByPage(ctx context.Context, in *ListByPageRequest, opts ...grpc.CallOption) (*PostDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDetailsResponse)
	err := c.cc.Invoke(ctx, PostService_ListByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListByPageAndUid(ctx context.Context, in *ListByPageAndUidRequest, opts ...grpc.CallOption) (*PostBriefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostBriefsResponse)
	err := c.cc.Invoke(ctx, PostService_ListByPageAndUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListByPageAndTag(ctx context.Context, in *ListByPageAndTagRequest, opts ...grpc.CallOption) (*PostDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDetailsResponse)
	err := c.cc.Invoke(ctx, PostService_ListByPageAndTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Belong(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*BelongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BelongResponse)
	err := c.cc.Invoke(ctx, PostService_Belong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Delete(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostEmptyResponse)
	err := c.cc.Invoke(ctx, PostService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Like(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostEmptyResponse)
	err := c.cc.Invoke(ctx, PostService_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Unlike(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostEmptyResponse)
	err := c.cc.Invoke(ctx, PostService_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) IfLike(ctx context.Context, in *PostCommonRequest, opts ...grpc.CallOption) (*IfLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IfLikeResponse)
	err := c.cc.Invoke(ctx, PostService_IfLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, PostService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*PostEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostEmptyResponse)
	err := c.cc.Invoke(ctx, PostService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListCommentByPage(ctx context.Context, in *ListCommentByPageRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, PostService_ListCommentByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListRepliesByPage(ctx context.Context, in *ListReplyByPageRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, PostService_ListRepliesByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CheckCommentDeleteAuth(ctx context.Context, in *CommentBelongRequest, opts ...grpc.CallOption) (*BelongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BelongResponse)
	err := c.cc.Invoke(ctx, PostService_CheckCommentDeleteAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PostService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
// All implementations must embed UnimplementedPostServiceServer
// for forward compatibility.
type PostServiceServer interface {
	// 创建帖子
	Create(context.Context, *CreatePostRequest) (*PostDetail, error)
	// 根据帖子 ID 查询帖子详情
	GetDetailByID(context.Context, *GetDetailByIDRequest) (*PostDetail, error)
	// 根据帖子 ID 查询帖子摘要
	GetBriefByID(context.Context, *GetBriefByIDRequest) (*PostBrief, error)
	// 返回推荐帖子
	Top(context.Context, *PostEmptyRequest) (*TopResponse, error)
	// 更新帖子
	Update(context.Context, *UpdateRequest) (*PostEmptyResponse, error)
	// 按页查询帖子
	ListByPage(context.Context, *ListByPageRequest) (*PostDetailsResponse, error)
	// 按页 + 用户 ID 查询用户发表的帖子
	ListByPageAndUid(context.Context, *ListByPageAndUidRequest) (*PostBriefsResponse, error)
	// 按页 + Tag 查询该 Tag 的帖子
	ListByPageAndTag(context.Context, *ListByPageAndTagRequest) (*PostDetailsResponse, error)
	// 查询帖子是否属于用户
	Belong(context.Context, *PostCommonRequest) (*BelongResponse, error)
	// 删除帖子
	Delete(context.Context, *PostCommonRequest) (*PostEmptyResponse, error)
	// 点赞帖子
	Like(context.Context, *PostCommonRequest) (*PostEmptyResponse, error)
	// 取消点赞帖子
	Unlike(context.Context, *PostCommonRequest) (*PostEmptyResponse, error)
	// 查询用户是否点过赞
	IfLike(context.Context, *PostCommonRequest) (*IfLikeResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*PostEmptyResponse, error)
	// 根据 PostID 按页获取文章主评论
	ListCommentByPage(context.Context, *ListCommentByPageRequest) (*CommentsResponse, error)
	// 根据 CommentID 按页获取评论的回复
	ListRepliesByPage(context.Context, *ListReplyByPageRequest) (*CommentsResponse, error)
	// 评论是否属于用户
	CheckCommentDeleteAuth(context.Context, *CommentBelongRequest) (*BelongResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPostServiceServer()
}

// UnimplementedPostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostServiceServer struct{}

func (UnimplementedPostServiceServer) Create(context.Context, *CreatePostRequest) (*PostDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPostServiceServer) GetDetailByID(context.Context, *GetDetailByIDRequest) (*PostDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailByID not implemented")
}
func (UnimplementedPostServiceServer) GetBriefByID(context.Context, *GetBriefByIDRequest) (*PostBrief, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBriefByID not implemented")
}
func (UnimplementedPostServiceServer) Top(context.Context, *PostEmptyRequest) (*TopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Top not implemented")
}
func (UnimplementedPostServiceServer) Update(context.Context, *UpdateRequest) (*PostEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPostServiceServer) ListByPage(context.Context, *ListByPageRequest) (*PostDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPage not implemented")
}
func (UnimplementedPostServiceServer) ListByPageAndUid(context.Context, *ListByPageAndUidRequest) (*PostBriefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPageAndUid not implemented")
}
func (UnimplementedPostServiceServer) ListByPageAndTag(context.Context, *ListByPageAndTagRequest) (*PostDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPageAndTag not implemented")
}
func (UnimplementedPostServiceServer) Belong(context.Context, *PostCommonRequest) (*BelongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Belong not implemented")
}
func (UnimplementedPostServiceServer) Delete(context.Context, *PostCommonRequest) (*PostEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPostServiceServer) Like(context.Context, *PostCommonRequest) (*PostEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedPostServiceServer) Unlike(context.Context, *PostCommonRequest) (*PostEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedPostServiceServer) IfLike(context.Context, *PostCommonRequest) (*IfLikeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IfLike not implemented")
}
func (UnimplementedPostServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedPostServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*PostEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedPostServiceServer) ListCommentByPage(context.Context, *ListCommentByPageRequest) (*CommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommentByPage not implemented")
}
func (UnimplementedPostServiceServer) ListRepliesByPage(context.Context, *ListReplyByPageRequest) (*CommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepliesByPage not implemented")
}
func (UnimplementedPostServiceServer) CheckCommentDeleteAuth(context.Context, *CommentBelongRequest) (*BelongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCommentDeleteAuth not implemented")
}
func (UnimplementedPostServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPostServiceServer) mustEmbedUnimplementedPostServiceServer() {}
func (UnimplementedPostServiceServer) testEmbeddedByValue()                     {}

// UnsafePostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostServiceServer will
// result in compilation errors.
type UnsafePostServiceServer interface {
	mustEmbedUnimplementedPostServiceServer()
}

func RegisterPostServiceServer(s grpc.ServiceRegistrar, srv PostServiceServer) {
	// If the following call panics, it indicates UnimplementedPostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostService_ServiceDesc, srv)
}

func _PostService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Create(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetDetailByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetDetailByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetDetailByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetDetailByID(ctx, req.(*GetDetailByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetBriefByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBriefByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetBriefByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetBriefByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetBriefByID(ctx, req.(*GetBriefByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Top_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Top(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Top_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Top(ctx, req.(*PostEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListByPage(ctx, req.(*ListByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListByPageAndUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPageAndUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListByPageAndUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListByPageAndUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListByPageAndUid(ctx, req.(*ListByPageAndUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListByPageAndTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPageAndTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListByPageAndTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListByPageAndTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListByPageAndTag(ctx, req.(*ListByPageAndTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Belong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Belong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Belong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Belong(ctx, req.(*PostCommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Delete(ctx, req.(*PostCommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Like(ctx, req.(*PostCommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Unlike(ctx, req.(*PostCommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_IfLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).IfLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_IfLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).IfLike(ctx, req.(*PostCommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListCommentByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListCommentByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListCommentByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListCommentByPage(ctx, req.(*ListCommentByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListRepliesByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplyByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListRepliesByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListRepliesByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListRepliesByPage(ctx, req.(*ListReplyByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CheckCommentDeleteAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentBelongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CheckCommentDeleteAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_CheckCommentDeleteAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CheckCommentDeleteAuth(ctx, req.(*CommentBelongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostService_ServiceDesc is the grpc.ServiceDesc for PostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.v1.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PostService_Create_Handler,
		},
		{
			MethodName: "GetDetailByID",
			Handler:    _PostService_GetDetailByID_Handler,
		},
		{
			MethodName: "GetBriefByID",
			Handler:    _PostService_GetBriefByID_Handler,
		},
		{
			MethodName: "Top",
			Handler:    _PostService_Top_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PostService_Update_Handler,
		},
		{
			MethodName: "ListByPage",
			Handler:    _PostService_ListByPage_Handler,
		},
		{
			MethodName: "ListByPageAndUid",
			Handler:    _PostService_ListByPageAndUid_Handler,
		},
		{
			MethodName: "ListByPageAndTag",
			Handler:    _PostService_ListByPageAndTag_Handler,
		},
		{
			MethodName: "Belong",
			Handler:    _PostService_Belong_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PostService_Delete_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _PostService_Like_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _PostService_Unlike_Handler,
		},
		{
			MethodName: "IfLike",
			Handler:    _PostService_IfLike_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostService_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _PostService_DeleteComment_Handler,
		},
		{
			MethodName: "ListCommentByPage",
			Handler:    _PostService_ListCommentByPage_Handler,
		},
		{
			MethodName: "ListRepliesByPage",
			Handler:    _PostService_ListRepliesByPage_Handler,
		},
		{
			MethodName: "CheckCommentDeleteAuth",
			Handler:    _PostService_CheckCommentDeleteAuth_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PostService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/post/v1/post.proto",
}
