// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/post/v1/post.proto

package post_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ViewCount     uint64                 `protobuf:"varint,2,opt,name=ViewCount,proto3" json:"ViewCount,omitempty"`
	LikeCount     uint64                 `protobuf:"varint,3,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	CommentCount  uint64                 `protobuf:"varint,4,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	ContentType   uint32                 `protobuf:"varint,7,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UserID        int64                  `protobuf:"varint,9,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetail) Reset() {
	*x = PostDetail{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetail) ProtoMessage() {}

func (x *PostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetail.ProtoReflect.Descriptor instead.
func (*PostDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostDetail) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PostDetail) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostDetail) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostDetail) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostDetail) GetContentType() uint32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *PostDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PostDetail) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PostDetail) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Abstract      string                 `protobuf:"bytes,6,opt,name=Abstract,proto3" json:"Abstract,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UserID        int64                  `protobuf:"varint,9,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBrief) Reset() {
	*x = PostBrief{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBrief) ProtoMessage() {}

func (x *PostBrief) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBrief.ProtoReflect.Descriptor instead.
func (*PostBrief) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostBrief) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PostBrief) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostBrief) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *PostBrief) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PostBrief) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type TopPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPost) Reset() {
	*x = TopPost{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPost) ProtoMessage() {}

func (x *TopPost) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPost.ProtoReflect.Descriptor instead.
func (*TopPost) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{2}
}

func (x *TopPost) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TopPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopPost) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	ContentType   uint32                 `protobuf:"varint,4,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetContentType() uint32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetDetailByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	AddViewCnt    bool                   `protobuf:"varint,2,opt,name=AddViewCnt,proto3" json:"AddViewCnt,omitempty"` // 是否加浏览量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailByIDRequest) Reset() {
	*x = GetDetailByIDRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailByIDRequest) ProtoMessage() {}

func (x *GetDetailByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDetailByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetDetailByIDRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *GetDetailByIDRequest) GetAddViewCnt() bool {
	if x != nil {
		return x.AddViewCnt
	}
	return false
}

type GetBriefByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBriefByIDRequest) Reset() {
	*x = GetBriefByIDRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBriefByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBriefByIDRequest) ProtoMessage() {}

func (x *GetBriefByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBriefByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBriefByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{5}
}

func (x *GetBriefByIDRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *UpdateRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListByPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        uint32                 `protobuf:"varint,1,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPageRequest) Reset() {
	*x = ListByPageRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPageRequest) ProtoMessage() {}

func (x *ListByPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPageRequest.ProtoReflect.Descriptor instead.
func (*ListByPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{7}
}

func (x *ListByPageRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListByPageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListByPageAndUidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PageNo        uint32                 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPageAndUidRequest) Reset() {
	*x = ListByPageAndUidRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPageAndUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPageAndUidRequest) ProtoMessage() {}

func (x *ListByPageAndUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPageAndUidRequest.ProtoReflect.Descriptor instead.
func (*ListByPageAndUidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{8}
}

func (x *ListByPageAndUidRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ListByPageAndUidRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListByPageAndUidRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListByPageAndTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	PageNo        uint32                 `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPageAndTagRequest) Reset() {
	*x = ListByPageAndTagRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPageAndTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPageAndTagRequest) ProtoMessage() {}

func (x *ListByPageAndTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPageAndTagRequest.ProtoReflect.Descriptor instead.
func (*ListByPageAndTagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{9}
}

func (x *ListByPageAndTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListByPageAndTagRequest) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListByPageAndTagRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PostDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	PostDetails   []*PostDetail          `protobuf:"bytes,2,rep,name=PostDetails,proto3" json:"PostDetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetailsResponse) Reset() {
	*x = PostDetailsResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetailsResponse) ProtoMessage() {}

func (x *PostDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetailsResponse.ProtoReflect.Descriptor instead.
func (*PostDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{10}
}

func (x *PostDetailsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PostDetailsResponse) GetPostDetails() []*PostDetail {
	if x != nil {
		return x.PostDetails
	}
	return nil
}

type PostBriefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	PostBriefs    []*PostBrief           `protobuf:"bytes,2,rep,name=PostBriefs,proto3" json:"PostBriefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBriefsResponse) Reset() {
	*x = PostBriefsResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBriefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBriefsResponse) ProtoMessage() {}

func (x *PostBriefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBriefsResponse.ProtoReflect.Descriptor instead.
func (*PostBriefsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{11}
}

func (x *PostBriefsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PostBriefsResponse) GetPostBriefs() []*PostBrief {
	if x != nil {
		return x.PostBriefs
	}
	return nil
}

type PostCommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommonRequest) Reset() {
	*x = PostCommonRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommonRequest) ProtoMessage() {}

func (x *PostCommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommonRequest.ProtoReflect.Descriptor instead.
func (*PostCommonRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{12}
}

func (x *PostCommonRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *PostCommonRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PostEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostEmptyRequest) Reset() {
	*x = PostEmptyRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEmptyRequest) ProtoMessage() {}

func (x *PostEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEmptyRequest.ProtoReflect.Descriptor instead.
func (*PostEmptyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{13}
}

type BelongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BelongResponse) Reset() {
	*x = BelongResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BelongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BelongResponse) ProtoMessage() {}

func (x *BelongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BelongResponse.ProtoReflect.Descriptor instead.
func (*BelongResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{14}
}

func (x *BelongResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type TopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopPosts      []*TopPost             `protobuf:"bytes,1,rep,name=TopPosts,proto3" json:"TopPosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopResponse) Reset() {
	*x = TopResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopResponse) ProtoMessage() {}

func (x *TopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopResponse.ProtoReflect.Descriptor instead.
func (*TopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{15}
}

func (x *TopResponse) GetTopPosts() []*TopPost {
	if x != nil {
		return x.TopPosts
	}
	return nil
}

type GetPostByTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeAt        string                 `protobuf:"bytes,1,opt,name=TimeAt,proto3" json:"TimeAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByTimeRequest) Reset() {
	*x = GetPostByTimeRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByTimeRequest) ProtoMessage() {}

func (x *GetPostByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByTimeRequest.ProtoReflect.Descriptor instead.
func (*GetPostByTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{16}
}

func (x *GetPostByTimeRequest) GetTimeAt() string {
	if x != nil {
		return x.TimeAt
	}
	return ""
}

type PostIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IDs           []int64                `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostIDs) Reset() {
	*x = PostIDs{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostIDs) ProtoMessage() {}

func (x *PostIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostIDs.ProtoReflect.Descriptor instead.
func (*PostIDs) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{17}
}

func (x *PostIDs) GetIDs() []int64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type PostEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostEmptyResponse) Reset() {
	*x = PostEmptyResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEmptyResponse) ProtoMessage() {}

func (x *PostEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEmptyResponse.ProtoReflect.Descriptor instead.
func (*PostEmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{18}
}

type ExistPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistPostRequest) Reset() {
	*x = ExistPostRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistPostRequest) ProtoMessage() {}

func (x *ExistPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistPostRequest.ProtoReflect.Descriptor instead.
func (*ExistPostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{19}
}

func (x *ExistPostRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

type ExistPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=Exist,proto3" json:"Exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistPostResponse) Reset() {
	*x = ExistPostResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistPostResponse) ProtoMessage() {}

func (x *ExistPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistPostResponse.ProtoReflect.Descriptor instead.
func (*ExistPostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{20}
}

func (x *ExistPostResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type CheckPostAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostID        int64                  `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostAuthRequest) Reset() {
	*x = CheckPostAuthRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostAuthRequest) ProtoMessage() {}

func (x *CheckPostAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostAuthRequest.ProtoReflect.Descriptor instead.
func (*CheckPostAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{21}
}

func (x *CheckPostAuthRequest) GetPostID() int64 {
	if x != nil {
		return x.PostID
	}
	return 0
}

func (x *CheckPostAuthRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CheckPostAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=Exist,proto3" json:"Exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostAuthResponse) Reset() {
	*x = CheckPostAuthResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostAuthResponse) ProtoMessage() {}

func (x *CheckPostAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostAuthResponse.ProtoReflect.Descriptor instead.
func (*CheckPostAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{22}
}

func (x *CheckPostAuthResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{23}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_post_v1_post_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_post_v1_post_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_post_v1_post_proto_rawDescGZIP(), []int{24}
}

var File_api_proto_post_v1_post_proto protoreflect.FileDescriptor

const file_api_proto_post_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/post/v1/post.proto\x12\apost.v1\"\x98\x02\n" +
	"\n" +
	"PostDetail\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tViewCount\x18\x02 \x01(\x04R\tViewCount\x12\x1c\n" +
	"\tLikeCount\x18\x03 \x01(\x04R\tLikeCount\x12\"\n" +
	"\fCommentCount\x18\x04 \x01(\x04R\fCommentCount\x12\x14\n" +
	"\x05Title\x18\x05 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x06 \x01(\tR\aContent\x12 \n" +
	"\vContentType\x18\a \x01(\rR\vContentType\x12\x1c\n" +
	"\tCreatedAt\x18\b \x01(\tR\tCreatedAt\x12\x16\n" +
	"\x06UserID\x18\t \x01(\x03R\x06UserID\x12\x12\n" +
	"\x04Tags\x18\n" +
	" \x03(\tR\x04Tags\"\x83\x01\n" +
	"\tPostBrief\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x05 \x01(\tR\x05Title\x12\x1a\n" +
	"\bAbstract\x18\x06 \x01(\tR\bAbstract\x12\x1c\n" +
	"\tCreatedAt\x18\b \x01(\tR\tCreatedAt\x12\x16\n" +
	"\x06UserID\x18\t \x01(\x03R\x06UserID\"E\n" +
	"\aTopPost\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Score\x18\x03 \x01(\x02R\x05Score\"\x91\x01\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12 \n" +
	"\vContentType\x18\x04 \x01(\rR\vContentType\x12\x12\n" +
	"\x04Tags\x18\x05 \x03(\tR\x04Tags\"N\n" +
	"\x14GetDetailByIDRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x1e\n" +
	"\n" +
	"AddViewCnt\x18\x02 \x01(\bR\n" +
	"AddViewCnt\"-\n" +
	"\x13GetBriefByIDRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\"\x83\x01\n" +
	"\rUpdateRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x12\n" +
	"\x04Tags\x18\x05 \x03(\tR\x04Tags\"G\n" +
	"\x11ListByPageRequest\x12\x16\n" +
	"\x06PageNo\x18\x01 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x02 \x01(\rR\bPageSize\"e\n" +
	"\x17ListByPageAndUidRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\rR\bPageSize\"_\n" +
	"\x17ListByPageAndTagRequest\x12\x10\n" +
	"\x03Tag\x18\x01 \x01(\tR\x03Tag\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\rR\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\rR\bPageSize\"b\n" +
	"\x13PostDetailsResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x04R\x05Count\x125\n" +
	"\vPostDetails\x18\x02 \x03(\v2\x13.post.v1.PostDetailR\vPostDetails\"^\n" +
	"\x12PostBriefsResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x04R\x05Count\x122\n" +
	"\n" +
	"PostBriefs\x18\x02 \x03(\v2\x12.post.v1.PostBriefR\n" +
	"PostBriefs\"C\n" +
	"\x11PostCommonRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"\x12\n" +
	"\x10PostEmptyRequest\"(\n" +
	"\x0eBelongResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\";\n" +
	"\vTopResponse\x12,\n" +
	"\bTopPosts\x18\x01 \x03(\v2\x10.post.v1.TopPostR\bTopPosts\".\n" +
	"\x14GetPostByTimeRequest\x12\x16\n" +
	"\x06TimeAt\x18\x01 \x01(\tR\x06TimeAt\"\x1b\n" +
	"\aPostIDs\x12\x10\n" +
	"\x03IDs\x18\x01 \x03(\x03R\x03IDs\"\x13\n" +
	"\x11PostEmptyResponse\"*\n" +
	"\x10ExistPostRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\")\n" +
	"\x11ExistPostResponse\x12\x14\n" +
	"\x05Exist\x18\x01 \x01(\bR\x05Exist\"F\n" +
	"\x14CheckPostAuthRequest\x12\x16\n" +
	"\x06PostID\x18\x01 \x01(\x03R\x06PostID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"-\n" +
	"\x15CheckPostAuthResponse\x12\x14\n" +
	"\x05Exist\x18\x01 \x01(\bR\x05Exist\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2\xd5\a\n" +
	"\vPostService\x129\n" +
	"\x06Create\x12\x1a.post.v1.CreatePostRequest\x1a\x13.post.v1.PostDetail\x12C\n" +
	"\rGetDetailByID\x12\x1d.post.v1.GetDetailByIDRequest\x1a\x13.post.v1.PostDetail\x12@\n" +
	"\fGetBriefByID\x12\x1c.post.v1.GetBriefByIDRequest\x1a\x12.post.v1.PostBrief\x126\n" +
	"\x03Top\x12\x19.post.v1.PostEmptyRequest\x1a\x14.post.v1.TopResponse\x12@\n" +
	"\rGetPostByTime\x12\x1d.post.v1.GetPostByTimeRequest\x1a\x10.post.v1.PostIDs\x12<\n" +
	"\x06Update\x12\x16.post.v1.UpdateRequest\x1a\x1a.post.v1.PostEmptyResponse\x12F\n" +
	"\n" +
	"ListByPage\x12\x1a.post.v1.ListByPageRequest\x1a\x1c.post.v1.PostDetailsResponse\x12Q\n" +
	"\x10ListByPageAndUid\x12 .post.v1.ListByPageAndUidRequest\x1a\x1b.post.v1.PostBriefsResponse\x12R\n" +
	"\x10ListByPageAndTag\x12 .post.v1.ListByPageAndTagRequest\x1a\x1c.post.v1.PostDetailsResponse\x12=\n" +
	"\x06Belong\x12\x1a.post.v1.PostCommonRequest\x1a\x17.post.v1.BelongResponse\x12@\n" +
	"\x06Delete\x12\x1a.post.v1.PostCommonRequest\x1a\x1a.post.v1.PostEmptyResponse\x12B\n" +
	"\tExistPost\x12\x19.post.v1.ExistPostRequest\x1a\x1a.post.v1.ExistPostResponse\x12N\n" +
	"\rCheckPostAuth\x12\x1d.post.v1.CheckPostAuthRequest\x1a\x1e.post.v1.CheckPostAuthResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.post.v1.HealthCheckRequest\x1a\x1c.post.v1.HealthCheckResponseB<Z:github.com/yzletter/go-postery/api/proto/post/v1;post_grpcb\x06proto3"

var (
	file_api_proto_post_v1_post_proto_rawDescOnce sync.Once
	file_api_proto_post_v1_post_proto_rawDescData []byte
)

func file_api_proto_post_v1_post_proto_rawDescGZIP() []byte {
	file_api_proto_post_v1_post_proto_rawDescOnce.Do(func() {
		file_api_proto_post_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_post_v1_post_proto_rawDesc), len(file_api_proto_post_v1_post_proto_rawDesc)))
	})
	return file_api_proto_post_v1_post_proto_rawDescData
}

var file_api_proto_post_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_post_v1_post_proto_goTypes = []any{
	(*PostDetail)(nil),              // 0: post.v1.PostDetail
	(*PostBrief)(nil),               // 1: post.v1.PostBrief
	(*TopPost)(nil),                 // 2: post.v1.TopPost
	(*CreatePostRequest)(nil),       // 3: post.v1.CreatePostRequest
	(*GetDetailByIDRequest)(nil),    // 4: post.v1.GetDetailByIDRequest
	(*GetBriefByIDRequest)(nil),     // 5: post.v1.GetBriefByIDRequest
	(*UpdateRequest)(nil),           // 6: post.v1.UpdateRequest
	(*ListByPageRequest)(nil),       // 7: post.v1.ListByPageRequest
	(*ListByPageAndUidRequest)(nil), // 8: post.v1.ListByPageAndUidRequest
	(*ListByPageAndTagRequest)(nil), // 9: post.v1.ListByPageAndTagRequest
	(*PostDetailsResponse)(nil),     // 10: post.v1.PostDetailsResponse
	(*PostBriefsResponse)(nil),      // 11: post.v1.PostBriefsResponse
	(*PostCommonRequest)(nil),       // 12: post.v1.PostCommonRequest
	(*PostEmptyRequest)(nil),        // 13: post.v1.PostEmptyRequest
	(*BelongResponse)(nil),          // 14: post.v1.BelongResponse
	(*TopResponse)(nil),             // 15: post.v1.TopResponse
	(*GetPostByTimeRequest)(nil),    // 16: post.v1.GetPostByTimeRequest
	(*PostIDs)(nil),                 // 17: post.v1.PostIDs
	(*PostEmptyResponse)(nil),       // 18: post.v1.PostEmptyResponse
	(*ExistPostRequest)(nil),        // 19: post.v1.ExistPostRequest
	(*ExistPostResponse)(nil),       // 20: post.v1.ExistPostResponse
	(*CheckPostAuthRequest)(nil),    // 21: post.v1.CheckPostAuthRequest
	(*CheckPostAuthResponse)(nil),   // 22: post.v1.CheckPostAuthResponse
	(*HealthCheckRequest)(nil),      // 23: post.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 24: post.v1.HealthCheckResponse
}
var file_api_proto_post_v1_post_proto_depIdxs = []int32{
	0,  // 0: post.v1.PostDetailsResponse.PostDetails:type_name -> post.v1.PostDetail
	1,  // 1: post.v1.PostBriefsResponse.PostBriefs:type_name -> post.v1.PostBrief
	2,  // 2: post.v1.TopResponse.TopPosts:type_name -> post.v1.TopPost
	3,  // 3: post.v1.PostService.Create:input_type -> post.v1.CreatePostRequest
	4,  // 4: post.v1.PostService.GetDetailByID:input_type -> post.v1.GetDetailByIDRequest
	5,  // 5: post.v1.PostService.GetBriefByID:input_type -> post.v1.GetBriefByIDRequest
	13, // 6: post.v1.PostService.Top:input_type -> post.v1.PostEmptyRequest
	16, // 7: post.v1.PostService.GetPostByTime:input_type -> post.v1.GetPostByTimeRequest
	6,  // 8: post.v1.PostService.Update:input_type -> post.v1.UpdateRequest
	7,  // 9: post.v1.PostService.ListByPage:input_type -> post.v1.ListByPageRequest
	8,  // 10: post.v1.PostService.ListByPageAndUid:input_type -> post.v1.ListByPageAndUidRequest
	9,  // 11: post.v1.PostService.ListByPageAndTag:input_type -> post.v1.ListByPageAndTagRequest
	12, // 12: post.v1.PostService.Belong:input_type -> post.v1.PostCommonRequest
	12, // 13: post.v1.PostService.Delete:input_type -> post.v1.PostCommonRequest
	19, // 14: post.v1.PostService.ExistPost:input_type -> post.v1.ExistPostRequest
	21, // 15: post.v1.PostService.CheckPostAuth:input_type -> post.v1.CheckPostAuthRequest
	23, // 16: post.v1.PostService.HealthCheck:input_type -> post.v1.HealthCheckRequest
	0,  // 17: post.v1.PostService.Create:output_type -> post.v1.PostDetail
	0,  // 18: post.v1.PostService.GetDetailByID:output_type -> post.v1.PostDetail
	1,  // 19: post.v1.PostService.GetBriefByID:output_type -> post.v1.PostBrief
	15, // 20: post.v1.PostService.Top:output_type -> post.v1.TopResponse
	17, // 21: post.v1.PostService.GetPostByTime:output_type -> post.v1.PostIDs
	18, // 22: post.v1.PostService.Update:output_type -> post.v1.PostEmptyResponse
	10, // 23: post.v1.PostService.ListByPage:output_type -> post.v1.PostDetailsResponse
	11, // 24: post.v1.PostService.ListByPageAndUid:output_type -> post.v1.PostBriefsResponse
	10, // 25: post.v1.PostService.ListByPageAndTag:output_type -> post.v1.PostDetailsResponse
	14, // 26: post.v1.PostService.Belong:output_type -> post.v1.BelongResponse
	18, // 27: post.v1.PostService.Delete:output_type -> post.v1.PostEmptyResponse
	20, // 28: post.v1.PostService.ExistPost:output_type -> post.v1.ExistPostResponse
	22, // 29: post.v1.PostService.CheckPostAuth:output_type -> post.v1.CheckPostAuthResponse
	24, // 30: post.v1.PostService.HealthCheck:output_type -> post.v1.HealthCheckResponse
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_post_v1_post_proto_init() }
func file_api_proto_post_v1_post_proto_init() {
	if File_api_proto_post_v1_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_post_v1_post_proto_rawDesc), len(file_api_proto_post_v1_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_post_v1_post_proto_goTypes,
		DependencyIndexes: file_api_proto_post_v1_post_proto_depIdxs,
		MessageInfos:      file_api_proto_post_v1_post_proto_msgTypes,
	}.Build()
	File_api_proto_post_v1_post_proto = out.File
	file_api_proto_post_v1_post_proto_goTypes = nil
	file_api_proto_post_v1_post_proto_depIdxs = nil
}
